### PR TITLE
Add a legacy mode to revert the ccompat API to use globalId instead of contentId

### PR DESCRIPTION
**Pull request by EricWittmann**

### CODE REVIEW

**Review by famartinrh — APPROVED** [review]
LGTM, good job

**Review by carlesarnal — APPROVED** [review]
LGTM

**Comment by EricWittmann** [comment]
@famartinrh Do you have any suggestions about what we might be able to do for testing this?  Anything quick we could create?

**Comment by famartinrh** [comment]
we also want to merge this with master

**Comment by EricWittmann** [comment]
done

**Pull request merged**
