### PR TITLE
Make AvroConverter look up schema version #3810

### PR DESCRIPTION
**Pull request by forsberg**
Schema Version is passed into Kafka Connect schema.

This is required for some connectors to work with multiple versions of same schema.

VERY MUCH a draft, pushing to get some CI.

### CODE REVIEW

**Comment by carlesarnal** [comment]
@forsberg First of all, thanks for the contribution. I have fixed a few problems with the CI build, please, update your branch accordingly.

**Comment by carlesarnal** [comment]
@forsberg now you have some legit Ci failures :).

**Comment by forsberg** [comment]
> @forsberg now you have some legit Ci failures :).

That's GREAT! :-)

I also have some trouble trying to run the integration tests locally as mentioned in https://github.com/Apicurio/apicurio-registry/discussions/3828, perhaps you could give me a hint there on what I'm doing wrong - that would certainly help in fixing them.

Sorry for being such a java noob, I'm sure it's something obvious.

**Comment by carlesarnal** [comment]
> > @forsberg now you have some legit Ci failures :).
> 
> That's GREAT! :-)
> 
> I also have some trouble trying to run the integration tests locally as mentioned in #3828, perhaps you could give me a hint there on what I'm doing wrong - that would certainly help in fixing them.
> 
> Sorry for being such a java noob, I'm sure it's something obvious.

Hey, no need to sorry, I missed the discussion, you have now an answer there that should help fixing them :).

**Comment by carlesarnal** [comment]
> > > @forsberg now you have some legit Ci failures :).
> > 
> > 
> > That's GREAT! :-)
> > I also have some trouble trying to run the integration tests locally as mentioned in #3828, perhaps you could give me a hint there on what I'm doing wrong - that would certainly help in fixing them.
> > Sorry for being such a java noob, I'm sure it's something obvious.
> 
> Hey, no need to sorry, I missed the discussion, you have now an answer there that should help fixing them :).

@forsberg do you need any help?

**Comment by forsberg** [comment]
Sorry about the low progress rate, I have a local version that fixed our most critical use case, but the code is still missing a few paths, and tests etc are not in place. With your hints, integration tests seem to work now though, so that's good.

Mostly, this work has slipped down the prio list due to other assignments, but it's not forgotten.

**Comment by carlesarnal** [comment]
Hey @forsberg I'm closing this for now as it seems stale. If you resume the work in the future, please just re-open!

**Comment by forsberg** [comment]
Yeah, sorry. It's slipped down my prio list, but sooner or later it'll make it to the top. I'm relying on this change in production, so I really want it upstream.

**Pull request closed without merging**
