### PR TITLE
Updates to the UI to support federation

### PR DESCRIPTION
**Pull request by EricWittmann**
Some things that have been changed:

1. Got rid of Lerna.  Now everything is in just one package
2. Export all Page components also as Federated components
3. Upgraded Patternfly to v4
4. Some config updates to support federation of the page components

### CODE REVIEW

**Comment by paoloantinori** [comment]
do we feel lucky to upgrade PatternFly before 2.0GA ?

**Comment by paoloantinori** [comment]
retest this please

**Comment by EricWittmann** [comment]
@paoloantinori - 2.0 GA will be built off our `2.0.x` branch and so will not include this change.

**Comment by EricWittmann** [comment]
@famartinrh Do you want to wait on merging this until the tests are updated?  Or should I go ahead with the merge and the UI tests can get fixed up later?

**Comment by famartinrh** [comment]
it would be nice to update the UI tests ASAP

**Pull request merged**
