### PR TITLE
CLI refactoring 2.0

### PR DESCRIPTION
**Pull request by famartinrh**
This PR modifies the CLI to make it work with Quarkus and easily compile it to a native executable.
The datamodel for the v2 api has been modified as well in order for native compilation to work properly.

### CODE REVIEW

**Comment by famartinrh** [comment]
ok, no problem, just one thing, the changes to the data model classes consist of including a quarkus specific annotation. 
That is nice because adding that annotation we don't need anymore a quarkus extension for the client to work in native mode. However they are quarkus specific, in our case it's not a problem because the datamodel maven module already had that quarkus dependency, but for other people generating their datamodel classes won't be a valid option. Just saying this so when you implement this in studio just add the option to specify annotations(with the full package name) to be added to the datamodel.

**Comment by EricWittmann** [comment]
(oops, wrong button)

**Comment by EricWittmann** [comment]
> Just saying this so when you implement this in studio just add the option to specify annotations(with the full package name) to be added to the datamodel.

Yes this is exactly my plan.

**Comment by famartinrh** [comment]
now this should be perfect, I had to add the RegisterForReflection annotation to the enums, because the studio did not generate that

**Comment by EricWittmann** [comment]
Rats, I missed the enums.  I'll correct that in the codegen.

**Comment by EricWittmann** [comment]
OK enums fixed in the codegen.  :)  Merging this.  Thanks @famartinrh

**Review by EricWittmann — APPROVED** [review]

**Pull request merged**
