### PR TITLE
Refactoring Protobuf schema parser into separate module

### PR DESCRIPTION
**Pull request by blacktooth**
Refactoring to facilitate re-use and contributions. This is follow up to discussion on [issue](https://github.com/Apicurio/apicurio-registry/issues/1572).

### CODE REVIEW

**Comment by blacktooth** [comment]
Build seems to be failing post this [commit](https://github.com/Apicurio/apicurio-registry/commit/804e555e96c05279f9fecd8260cd335abd74bae3).

**Comment by carlesarnal** [comment]
@blacktooth you're missing some changes from master that fixes some failing tests. I have updated your or with those changes.

**Review by EricWittmann — APPROVED** [review]
This looks fine to me.  @jsenko any issues with this?

**Comment by blacktooth** [comment]
Thanks a lot Eric and Carles!

**Review by famartinrh — APPROVED** [review]
LGTM

**Review by jsenko — APPROVED** [review]
+1

**Pull request merged**
