### PR TITLE
chore: add a dockerfile to build and deploy

### PR DESCRIPTION
**Pull request by sbose78**
This Dockerfile builds the registry for use with an sql storage backend.
Based on https://github.com/Apicurio/apicurio-registry/blob/master/distro/docker/src/main/docker/Dockerfile.sql.jvm
and
https://github.com/Apicurio/apicurio-registry/blob/f0687e05e8b2a0d53d865071030068b2bd22523a/distro/docker/pom.xml#L18

### CODE REVIEW

**Comment by EricWittmann** [comment]
I think this might make more sense to put on the `mas-sr` branch. wdyt?  @Apicurio/developers

**Comment by riprasad** [comment]
@sbose78 we already have a dockerfile for the same here https://github.com/Apicurio/apicurio-registry/blob/mas-sr/distro/docker/src/main/docker/Dockerfile.sql.jvm

and a script that builds and deploys the image to quay here https://github.com/Apicurio/apicurio-registry/blob/mas-sr/build-deploy.sh

Any specifc reason why we need this? The only difference is that the committed Dockerfile performs a multi-stage build

**Comment by riprasad** [comment]
LGTM and makes more sense to keep this in mas-sr

**Review by riprasad — APPROVED** [review]

**Comment by famartinrh** [comment]
I agree this makes more sense to have it only in `mas-sr` branch, as it's something mas specific. Btw I like this kind of dockerfiles :)

**Comment by EricWittmann** [comment]
Closing and awaiting a new PR to the `mas-sr` branch.

**Pull request closed without merging**
