### PR TITLE
Fix for issue #1479 - magic byte detection

### PR DESCRIPTION
**Pull request by famartinrh**
if we can include this in 2.x branch it would be ideal

### CODE REVIEW

**Comment by famartinrh** [comment]
Fix for issue #1479

**Review by EricWittmann — APPROVED** [review]

**Comment by EricWittmann** [comment]
Merged and cherry picked.

**Comment by famartinrh** [comment]
we should have waited for the test results

**Comment by famartinrh** [comment]
@EricWittmann I may have to add another commit, I think I broke some other things

**Pull request merged**
