### PR TITLE
add new doc section with more details on serdes config options

### PR DESCRIPTION
**Pull request by smccarthy-ie**

### CODE REVIEW

**Review by EricWittmann — CHANGES_REQUESTED** [review]
Looks good, although I wouldn't hate another column that maps the property name to the static field in the `SerdeConfig` class (which is what we expect developers to use when configuring their kafka apps).

**Comment by EricWittmann** [comment]
For reference: https://github.com/Apicurio/apicurio-registry/blob/2.0.x/serdes/serde-common/src/main/java/io/apicurio/registry/serde/SerdeConfig.java

**Comment by smccarthy-ie** [comment]
@EricWittmann OK, so for example, you mean add the `ARTIFACT_RESOLVER_STRATEGY`static field for the `apicurio.registry.schema-resolver` config property, and so on?

**Comment by smccarthy-ie** [comment]
@EricWittmann @famartinrh I've added those config constants as Eric suggested. Hope I've understood correctly? 

It makes for some monster-size 5 col tables, but I guess the user can max their display, so long as they are not viewing on their phone :)

**Comment by EricWittmann** [comment]
Awesome thanks!!

**Pull request merged**
