### PR TITLE
Infrastructure to validate the generated code for the api v2

### PR DESCRIPTION
**Pull request by andreaTP**
Opening in Draft as it depends on:
https://github.com/Apicurio/apicurio-codegen/pull/37

This PR checks that the generated code and the OpenApi spec are kept in sync using the codegen CLI in CI.

### CODE REVIEW

**Comment by EricWittmann** [comment]
I merged https://github.com/Apicurio/apicurio-codegen/pull/38 and did a release of that repo.  FYI

**Comment by andreaTP** [comment]
@EricWittmann sorry for the confusion, this PR depends on: https://github.com/Apicurio/apicurio-codegen/pull/37 not 38

**Comment by EricWittmann** [comment]
No problem.

This looks good to me.  What do you think about automatically re-generating the code whenever the openapi file changes and opening a PR?  Or is it possible for a check to update the existing PR?

**Comment by andreaTP** [comment]
>  What do you think about automatically re-generating the code whenever the openapi file changes and opening a PR? 

This is possible (giving to the CI enough permissions), but, ideally, the workflow should be "clean" e.g.:
if you commit changes to the `openapi.json` file the CI fails and you should re-generate the code before having a PR merged.
Or, I'm missing a use-case?

> Or is it possible for a check to update the existing PR?

This is an interesting approach indeed! I can have a look next week, but, possibly, we would need a GH bot for this task ( cc. @jsenko )

**Comment by EricWittmann** [comment]
> > What do you think about automatically re-generating the code whenever the openapi file changes and opening a PR?
> 
> This is possible (giving to the CI enough permissions), but, ideally, the workflow should be "clean" e.g.: if you commit changes to the `openapi.json` file the CI fails and you should re-generate the code before having a PR merged. Or, I'm missing a use-case?

Thinking more about it you are right.  We don't want to open a 2nd PR, that doesn't make sense.

> > Or is it possible for a check to update the existing PR?
> 
> This is an interesting approach indeed! I can have a look next week, but, possibly, we would need a GH bot for this task ( cc. @jsenko )

But this option may make sense.  What I'm trying to figure out is what's our best workflow starting from Apicurio Studio.  If we can modify a PR, then the flow might be:

1) Make changes to API using Studio
2) Use Studio to open a PR (on a new branch) with the changes to `openapi.json`
3) GH check/bot updates the PR with newly generated code
4) Pull down the new branch with the `openapi.json` changes and regenerated code
5) Make any needed impl changes
6) Push impl changes to branch
7) Profit!

I really want to encourage Studio (and eventually API Designer) as our contract-first approach to building our own APIs.

**Comment by andreaTP** [comment]
@EricWittmann your proposal starts to be intriguing!

What you are saying makes a lot of sense if (forgive my ignorance) we can have some kind of support for braches in Studio, I'm thinking about handling edge cases such as:
- in flight (e.g. not merged) PRs
- WIP/Draft and proposals that can or cannot be eventually merged 

Do you have any thoughts/ideas in this direction?

**Comment by EricWittmann** [comment]
> @EricWittmann your proposal starts to be intriguing!
> 
> What you are saying makes a lot of sense if (forgive my ignorance) we can have some kind of support for branches in Studio, I'm thinking about handling edge cases such as:
> 
>     * in flight (e.g. not merged) PRs
> 
>     * WIP/Draft and proposals that can or cannot be eventually merged
> 
> 
> Do you have any thoughts/ideas in this direction?

For API Designer (the reboot of Studio) we definitely want to support basic branching/merging.  In that case I think this "modify the PR" approach will work even better.

However, for the current version of Studio we don't have anything like that.  So I think **for now** we can simply modify the "Publish to Git" workflow in the current version of Studio to create a new branch + Pull Request (with random name).  [Note: the "Publish to Git" feature currently just commits the openapi.json file directly to the target branch specified]

In this way, we can work on the PR bot workflow without having proper branching/merging within Studio itself, but be in a good position to support that when we implement it in API Designer.

How does that sound?

**Comment by andreaTP** [comment]
Shaping up! I would like to play around with this workflow to have a real sense of it.

General comments regarding usability:
 - changing the "Publish to Git" command should be able to target repo forks (this has implications, of course ...)
 - for this workflow to be available to the users it shouldn't depend on a "bot workflow"
 
A couple of missing bits:
 - how do I link the proposed change with the Studio View of the spec?
 - should I save the spec with a different name(or something ...) for now? Or should you "edit" in draft mode all the time?

**Comment by andreaTP** [comment]
Meanwhile this PR is ready for final review (not the nice discussion that sparked here though 🙂 )

**Review by EricWittmann — APPROVED** [review]

**Pull request merged**
