### PR TITLE
Fix Settings feature enablement/disablement

### PR DESCRIPTION
**Pull request by marcantoine-bibeau**
'|| true'  ignore the Settings feature configuration

### CODE REVIEW

**Comment by EricWittmann** [comment]
So why change the default?

**Comment by marcantoine-bibeau** [comment]
> So why change the default?

Something 'OR' true = always true meaning there's no way to set to false. Even if I set false the configuration because if that, it is turned back to true

Or I'm missing something ?

**Comment by EricWittmann** [comment]
The only thing you missed was me being dumb.  :)

The pattern in that config service is to use the `||` operator to return a default when the value is not provided in the config object.  This works great for types that are not `boolean`.  So for example:

```typescript
    public artifactsUrl(): string {
        return registryConfig.artifacts.url || "http://localhost:8080/apis/registry/v3/";
    }
```

And it also works fine when the type is `boolean` and the default is `false`:

```typescript
    public authRbacEnabled(): boolean {
        return registryConfig.auth?.rbacEnabled || false;
    }
```

But as you've discovered (thanks!) it's no good when the type is `boolean` and we want a default of `true`.

I'm going to close this PR, because what it does is change the default value for `settings` to be `false`, and we want the default value to be `true`.  So I'm going to fix this problem with this code:

```typescript
    public featureSettings(): boolean {
        return this.features().settings === undefined ? true : this.features().settings as boolean;
    }
```

**Comment by EricWittmann** [comment]
Thanks @marcantoine-bibeau for finding this issue.  This PR is superseded by:

* https://github.com/Apicurio/apicurio-registry/pull/5194

**Pull request closed without merging**
