### PR TITLE
Add options for Protobuf schema parsing

### PR DESCRIPTION
**Pull request by hhkkxxx133**
As part of #1671 , this PR is to address missing options when parsing Protobuf schema.

### CODE REVIEW

**Comment by blacktooth** [comment]
Looks good to me!

**Review by carlesarnal — APPROVED** [review]
LGTM

**Comment by hhkkxxx133** [comment]
Any update on this?

**Comment by EricWittmann** [comment]
I'm running the checks again.  The failures looked unrelated.  If everything looks OK I'll merge soon.

**Comment by EricWittmann** [comment]
Please ping this PR again on Tuesday the 9th if I haven't merged it by then.  :)

**Pull request merged**
