### PR TITLE
Add new caching CRUD id strategy.

### PR DESCRIPTION
**Pull request by alesj**

### CODE REVIEW

**Comment by EricWittmann** [comment]
@alesj this is failing in CI

**Comment by alesj** [comment]
Error / stack-trace?

**Comment by EricWittmann** [comment]
@alesj https://circleci.com/api/v1.1/project/github/Apicurio/apicurio-registry/1235/output/106/0?file=true&allocation-id=5e95abe5416fdf488ec5797f-0-build%2F2B77BBDB

**Comment by alesj** [comment]
@EricWittmann @jsenko some strange JPA error ... together with liveness check ... ?

**Comment by EricWittmann** [comment]
This is perhaps what @cfoskin is also seeing in his build...

**Comment by EricWittmann** [comment]
Sadly `master` is passing but this PR is failing on the new test.  I'll try to test locally to see what I can figure out, but not sure when...

**Pull request merged**
