### PR TITLE
Proper rest date formats 833

### PR DESCRIPTION
**Pull request by carlesarnal**

### CODE REVIEW

**Comment by EricWittmann** [comment]
As a result of this change, what does the JSON payload from the REST API look like?

Also, did you test the UI to make sure that still works?

**Comment by carlesarnal** [comment]
> As a result of this change, what does the JSON payload from the REST API look like?

The payload is the same except for the fact that now the required dates (I've checked which ones in the OpenAPI spec) are being returned in `ISO-8601` format (e.g. 2021-01-13T14:12:57.529+00:00) since that's the default format when using the String shape against a `Date` object in Jackson.

> Also, did you test the UI to make sure that still works?

Yes, I haven't checked how the UI is parsing that info but according to what I've seen it's working fine.

**Comment by EricWittmann** [comment]
Any way to tighten that format up a bit?  We probably don't need the microsecond granularity.  :)  I'd prefer if we just had e.g. `2021-01-13T14:12:57Z`

**Comment by carlesarnal** [comment]
> Any way to tighten that format up a bit? We probably don't need the microsecond granularity. :) I'd prefer if we just had e.g. `2021-01-13T14:12:57Z`

Yes, you can add a pattern to the `JsonFormat` annotation. I'll change that.

**Review by EricWittmann — APPROVED** [review]

**Pull request merged**
