### PR TITLE
Use IoUtil - to get uniform handling of encoding.

### PR DESCRIPTION
**Pull request by alesj**

### CODE REVIEW

**Comment by EricWittmann** [comment]
Shouldn't this go on `1.1.x`?

**Comment by alesj** [comment]
Ah yes ... 
So I need 2 pull-requests ... one for master and one for 1.1.x ?

**Comment by EricWittmann** [comment]
No I think just submit a PR for `1.1.x` - we'll periodically merge `1.1.x` to `master`.

**Comment by EricWittmann** [comment]
Closing this PR as this change has been merged into `1.1.x`.

**Pull request closed without merging**
