### PR TITLE
Reduced the list of dependencies packaged in the Kafka Connector distro

### PR DESCRIPTION
**Pull request by EricWittmann**
See:  https://github.com/Apicurio/apicurio-registry/issues/497

### CODE REVIEW

**Comment by EricWittmann** [comment]
@jpechane What do you think?  :)

**Comment by jpechane** [comment]
@EricWittmann Great job, thanks a lot! I don't see any other unnecessary file in it and I've successfully tested the converter.

For product though I'd recommend to consider using the Kafka Connect Jackson version instead of bringing your own (as mentioned before it works with it).

In what varison (and schedule) do you plan to release this distro? We'd update our dependencies immediately.

**Comment by EricWittmann** [comment]
An upstream release (1.3.1.Final) will be done shortly.  I don't have a schedule for product.  Q4 is possible.

**Comment by EricWittmann** [comment]
@jpechane Upstream 1.3.1.Final has been released.

**Comment by jpechane** [comment]
Thanks, unfortunately somethin went wrong https://github.com/Apicurio/apicurio-registry/issues/864

**Comment by EricWittmann** [comment]
OK thanks @jpechane that's unfortunate.  We definitely need a good integration test for this distro.  @famartinrh is working on that!

**Comment by famartinrh** [comment]
@EricWittmann I successfully implemented a test for this in our k8s testsuite and I'm able to reproduce the error... https://gist.github.com/famartinrh/8db30fcb680e14021903a414aeed2c61 here a gist with the logs of the debezium pod in case it helps

**Pull request merged**
