### PR TITLE
Quarkus 1.7.0.Final + IBM api test fix

### PR DESCRIPTION
**Pull request by alesj**

### CODE REVIEW

**Review by ajborley — APPROVED** [review]
LGTM - thanks for fixing the ibmcompat test 👍

**Comment by EricWittmann** [comment]
Rebuilding now, but the build failed for this PR last time.  We'll see what happens this time... @alesj

**Comment by EricWittmann** [comment]
Still failing in CI - @alesj I assume this works ok for you locally?

**Comment by alesj** [comment]
Yes

What’s the problem / error?

**Comment by alesj** [comment]
OK, I see what the real problem is -- working on a fix.

**Pull request merged**
