### PR TITLE
Fetch records in retry as well.

### PR DESCRIPTION
**Pull request by alesj**

### CODE REVIEW

**Comment by EricWittmann** [comment]
We'll need to tie this back to a bug/issue with explanation if we want to merge it into the branch we're using for prod.  Do we have a bug reported that this is fixing?

**Comment by alesj** [comment]
Not really.
It just makes things more stable.
e.g. the Kafka storage wouldn’t die for any serialization issues (as would
now)

**Comment by EricWittmann** [comment]
Can you open a GitHub issue and write up a short explanation of the issue and how this fixed it and improves stability?  So I can point Paolo to it.

**Comment by EricWittmann** [comment]
@alesj I have cherry picked the commit with ID bbe3ba138173ab44afc7d6a1d30ca6c931670e1f and pushed it to master.  I'm closing this PR as done and will mark the GH issue as complete.

**Pull request closed without merging**
