### PR TITLE
Implemented multi-tenancy support in the SqlStorage layer [multiple DB schemas]

### PR DESCRIPTION
**Pull request by EricWittmann**
This is an alternative approach to multi-tenancy using separate sets of tables for each tenant.  This approach requires a provisioning step per-tenant, where the tables are created.

### CODE REVIEW

**Review by carlesarnal — APPROVED** [review]
LGTM

**Comment by EricWittmann** [comment]
@Apicurio/developers I think this PR should be a place where we can discuss the pros and cons of the two multi-tenancy approaches (TenantId column vs. multiple DB schemas).

I'd like to hear opinions/thoughts.

One obvious difference is that the tenantId column allows a wider variety of tenant IDs (fewer restrictions on that data vs. the name of a DB schema).

**Comment by EricWittmann** [comment]
Backup and restore of a single tenant is presumably much easier when using the multi-schema approach.

**Comment by EricWittmann** [comment]
The multi-schema approach requires a provisioning step (the DDL must be run once per tenant).  Nothing like that is required for the tenantId approach.

**Comment by carlesarnal** [comment]
Provisioning of multiple db instances is simpler in the multi-schema approach.

**Comment by EricWittmann** [comment]
> Provisioning of multiple db instances is simpler in the multi-schema approach.

How so?

**Comment by jsenko** [comment]
It is possible to create a custom CDI scope with a Quarkus extension, see http://dplatz.de/blog/2020/quarkus-custom-cdi-scope.html
The approach for defining the tenant scope in the PR seems OK, and the extension works in a similar way (thread locals), but we may want to consider using a native/standard approach.

**Review by jsenko — COMMENTED** [review]
It is possible to create a custom CDI scope with a Quarkus extension, see http://dplatz.de/blog/2020/quarkus-custom-cdi-scope.html
The approach for defining the tenant scope in the PR seems OK, and the extension works in a similar way (thread locals), but we may want to consider using a native/standard approach.

Other than that, LGTM.

**Pull request closed without merging**
