### PR TITLE
bring back serdes integration tests

### PR DESCRIPTION
**Pull request by famartinrh**

### CODE REVIEW

**Comment by famartinrh** [comment]
this results are actually expected because of a known bug in sql storage implementation, that is fixed in [this PR](https://github.com/EricWittmann/apicurio-registry/pull/10)

**Comment by EricWittmann** [comment]
This looks good - OK to merge this, @famartinrh ?

**Comment by famartinrh** [comment]
yes, please, merge this. Well I'll update this with master and you can merge it ?

**Comment by famartinrh** [comment]
ready to be merged @EricWittmann

**Pull request merged**
