### PR TITLE
Allow for mix of serdes, issue #172.

### PR DESCRIPTION
**Pull request by alesj**

### CODE REVIEW

**Comment by EricWittmann** [comment]
@alesj I rebased the PR but it fails CI.  Can you take a look?

**Comment by alesj** [comment]
What fails for you? SerdeMixTest?

**Comment by EricWittmann** [comment]
Yeah - failing in CircleCI and it fails for me locally as well:

```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.201 s - in io.apicurio.registry.RulesResourceTest
[INFO] Running io.apicurio.registry.SerdeMixTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.029 s <<< FAILURE! - in io.apicurio.registry.SerdeMixTest
[ERROR] testSerdeMix  Time elapsed: 0.029 s  <<< ERROR!
javax.ws.rs.WebApplicationException: Unknown error, status code 500
        at io.apicurio.registry.SerdeMixTest.testSerdeMix(SerdeMixTest.java:63)

[INFO] Running io.apicurio.registry.storage.RegistryStorageSmokeTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in io.apicurio.registry.storage.RegistryStorageSmokeTest
[INFO] Running io.apicurio.registry.SubjectsResourceTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in io.apicurio.registry.SubjectsResourceTest
[INFO] Running io.apicurio.registry.util.ArtifactTypeUtilTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in io.apicurio.registry.util.ArtifactTypeUtilTest
2019-12-02 07:26:05,869 INFO  [io.quarkus] (main) Quarkus stopped in 0.051s
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   SerdeMixTest.testSerdeMix:63 ▒ WebApplication Unknown error, status code 500
[INFO]
[ERROR] Tests run: 64, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for apicurio-registry 1.1.0-SNAPSHOT:
[INFO]
[INFO] apicurio-registry .................................. SUCCESS [  7.663 s]
[INFO] apicurio-registry-common ........................... SUCCESS [ 11.024 s]
[INFO] apicurio-registry-client ........................... SUCCESS [  5.246 s]
[INFO] apicurio-registry-utils-serde ...................... SUCCESS [  4.779 s]
[INFO] apicurio-registry-utils-converter .................. SUCCESS [  3.063 s]
[INFO] apicurio-registry-maven-plugin ..................... SUCCESS [  6.144 s]
[INFO] apicurio-registry-app .............................. FAILURE [ 37.726 s]
[INFO] apicurio-registry-utils-tools ...................... SKIPPED
[INFO] apicurio-registry-distro ........................... SKIPPED
[INFO] apicurio-registry-distro-docker .................... SKIPPED
[INFO] apicurio-registry-distro-docker-compose ............ SKIPPED
[INFO] apicurio-registry-distro-kubernetes-helm ........... SKIPPED
[INFO] apicurio-registry-distro-openshift-operator ........ SKIPPED
[INFO] apicurio-registry-distro-openshift-template ........ SKIPPED
[INFO] apicurio-registry-docs ............................. SKIPPED
[INFO] apicurio-registry-docs-rest-api .................... SKIPPED
[INFO] apicurio-registry-tests ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:18 min
[INFO] Finished at: 2019-12-02T07:26:06-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project apicurio-registry-app: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Eric\tmp\apicurio\apicurio-registry\app\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apicurio-registry-app
```

**Comment by alesj** [comment]
Hmmm ... strange, works for me.
Can you catch stack-trace somehow for this 500?

**Comment by EricWittmann** [comment]
Sure thing.  I'll report back.

**Comment by EricWittmann** [comment]
Here is the error.

```
[INFO] Running io.apicurio.registry.SerdeMixTest
2019-12-02 09:00:32,629 ERROR [io.api.reg.res.RegistryExceptionMapper] (executor-thread-1) com.fasterxml.jackson.core.JsonParseException: Unexpected character ('?' (code 65533 / 0xfffd)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"
?

common.proto!io.apicurio.registry.common.proto"
UUID

msb (

lsb (B)
!io.apicurio.registry.common.protoBCmmnbproto3"; line: 2, column: 2]: org.apache.avro.SchemaParseException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('?' (code 65533 / 0xfffd)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"
?

common.proto!io.apicurio.registry.common.proto"
UUID

msb (

lsb (B)
!io.apicurio.registry.common.protoBCmmnbproto3"; line: 2, column: 2]
        at org.apache.avro.Schema$Parser.parse(Schema.java:1398)
        at org.apache.avro.Schema$Parser.parse(Schema.java:1384)
        at io.apicurio.registry.content.canon.AvroContentCanonicalizer.canonicalize(AvroContentCanonicalizer.java:76)
        at io.apicurio.registry.storage.impl.AbstractMapRegistryStorage.getArtifactMetaData(AbstractMapRegistryStorage.java:283)
        at io.apicurio.registry.storage.impl.InMemoryRegistryStorage_Subclass.getArtifactMetaData$$superaccessor21(InMemoryRegistryStorage_Subclass.zig:4060)
        at io.apicurio.registry.storage.impl.InMemoryRegistryStorage_Subclass$$function$$21.apply(InMemoryRegistryStorage_Subclass$$function$$21.zig:59)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.apicurio.registry.metrics.PersistenceTimeoutReadinessInterceptor.intercept(PersistenceTimeoutReadinessInterceptor.java:27)
        at io.apicurio.registry.metrics.PersistenceTimeoutReadinessInterceptor_Bean.intercept(PersistenceTimeoutReadinessInterceptor_Bean.zig:177)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
        at io.apicurio.registry.metrics.PersistenceExceptionLivenessInterceptor.intercept(PersistenceExceptionLivenessInterceptor.java:48)
        at io.apicurio.registry.metrics.PersistenceExceptionLivenessInterceptor_Bean.intercept(PersistenceExceptionLivenessInterceptor_Bean.zig:178)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.apicurio.registry.storage.impl.InMemoryRegistryStorage_Subclass.getArtifactMetaData(InMemoryRegistryStorage_Subclass.zig:980)
        at io.apicurio.registry.storage.impl.InMemoryRegistryStorage_ClientProxy.getArtifactMetaData(InMemoryRegistryStorage_ClientProxy.zig:304)
        at io.apicurio.registry.storage.RegistryStorageProducer_ProducerMethod_realImpl_cf1c876861dd1c25dca504d30a12bfedeafd47bd_ClientProxy.getArtifactMetaData(RegistryStorageProducer_ProducerMethod_realImpl_cf1c876861dd1c25dca504d30a12bfedeafd47bd_ClientProxy.zig:364)
        at io.apicurio.registry.rest.ArtifactsResourceImpl.getArtifactMetaDataByContent(ArtifactsResourceImpl.java:320)
        at io.apicurio.registry.rest.ArtifactsResourceImpl_ClientProxy.getArtifactMetaDataByContent(ArtifactsResourceImpl_ClientProxy.zig:587)
        at sun.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
        at org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:122)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:110)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:122)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:594)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:468)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:421)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:423)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:391)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:365)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
        at io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:30)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:270)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:59)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:116)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:113)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1$1.call(UndertowDeploymentRecorder.java:475)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:250)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:59)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:82)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:669)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('?' (code 65533 / 0xfffd)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"
?

common.proto!io.apicurio.registry.common.proto"
UUID

msb (

lsb (B)
!io.apicurio.registry.common.protoBCmmnbproto3"; line: 2, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:591)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1902)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2380)
        at org.apache.avro.Schema$Parser.parse(Schema.java:1396)
        ... 86 more

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.042 s <<< FAILURE! - in io.apicurio.registry.SerdeMixTest
[ERROR] testSerdeMix  Time elapsed: 0.041 s  <<< ERROR!
javax.ws.rs.WebApplicationException: Unknown error, status code 500
        at io.apicurio.registry.SerdeMixTest.testSerdeMix(SerdeMixTest.java:63)

[INFO] Running io.apicurio.registry.storage.RegistryStorageSmokeTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in io.apicurio.registry.storage.RegistryStorageSmokeTest
[INFO] Running io.apicurio.registry.SubjectsResourceTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in io.apicurio.registry.SubjectsResourceTest
[INFO] Running io.apicurio.registry.util.ArtifactTypeUtilTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in io.apicurio.registry.util.ArtifactTypeUtilTest
2019-12-02 09:00:32,742 INFO  [io.quarkus] (main) Quarkus stopped in 0.043s
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   SerdeMixTest.testSerdeMix:63 ▒ WebApplication Unknown error, status code 500
[INFO]
[ERROR] Tests run: 64, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for apicurio-registry 1.1.0-SNAPSHOT:
[INFO]
[INFO] apicurio-registry .................................. SUCCESS [  2.002 s]
[INFO] apicurio-registry-common ........................... SUCCESS [  7.005 s]
[INFO] apicurio-registry-client ........................... SUCCESS [  2.711 s]
[INFO] apicurio-registry-utils-serde ...................... SUCCESS [  3.023 s]
[INFO] apicurio-registry-utils-converter .................. SUCCESS [  1.943 s]
[INFO] apicurio-registry-maven-plugin ..................... SUCCESS [  3.235 s]
[INFO] apicurio-registry-app .............................. FAILURE [ 25.695 s]
[INFO] apicurio-registry-utils-tools ...................... SKIPPED
[INFO] apicurio-registry-distro ........................... SKIPPED
[INFO] apicurio-registry-distro-docker .................... SKIPPED
[INFO] apicurio-registry-distro-docker-compose ............ SKIPPED
[INFO] apicurio-registry-distro-kubernetes-helm ........... SKIPPED
[INFO] apicurio-registry-distro-openshift-operator ........ SKIPPED
[INFO] apicurio-registry-distro-openshift-template ........ SKIPPED
[INFO] apicurio-registry-docs ............................. SKIPPED
[INFO] apicurio-registry-docs-rest-api .................... SKIPPED
[INFO] apicurio-registry-tests ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  46.513 s
[INFO] Finished at: 2019-12-02T09:00:33-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project apicurio-registry-app: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Eric\tmp\apicurio\apicurio-registry\app\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apicurio-registry-app
```

It's failing on Avro content canonicalization, but is perhaps expecting protobuf?  Hard to tell.  Let me know if you want me to add more debug info somewhere, or step through it.

**Comment by alesj** [comment]
Hmmm ... looks like some Proto schema stays in the registry, but we think it's Avro ...
Can you check a bit more ... since I cannot get it to reproduce ... ?

**Comment by EricWittmann** [comment]
Sure, give me some time.

**Pull request merged**
