### PR TITLE
Switch pr workflows to java 17

### PR DESCRIPTION
**Pull request by carlesarnal**

### CODE REVIEW

**Comment by EricWittmann** [comment]
@riprasad is there any way to have a matrix of different environments (i.e. multiple different java versions) for testing in the workflows?

**Comment by riprasad** [comment]
@EricWittmann Yes, we can utilize the matrix strategy to have multiple java versions.

**Comment by riprasad** [comment]
I have done the necessary changes on top of Carles's commit. Now, the builds should happen using both java 11 and 17

**Comment by carlesarnal** [comment]
Hey @riprasad, workflows are not running. Do you happen to know if I did anything wrong or if I need to do something else?

**Comment by riprasad** [comment]
@carlesarnal yea, that was because the path to the workflow was ignored for workflow triggers. I have changed that now. and looks like JDK 17 optio is not available with the action we are using for installing JDK

**Comment by carlesarnal** [comment]
> @carlesarnal yea, that was because the path to the workflow was ignored for workflow triggers. I have changed that now. and looks like JDK 17 optio is not available with the action we are using for installing JDK

Hm, that's relatively expected. It seems that the action we're using is not actively maintained, so perhaps we should switch to something else, maybe https://github.com/actions/setup-java?

**Pull request closed without merging**
