### PR TITLE
Throw specific exception 916

### PR DESCRIPTION
**Pull request by carlesarnal**

### CODE REVIEW

**Comment by carlesarnal** [comment]
@EricWittmann I'm not 100% happy with this but I think this worth a review. I've created new exception classes in this proposal. Do you think that worth to move the already existing ones to the common package and use them here as well? I think this second one is the right approach but wanted to ask before doing a change like that.

**Comment by EricWittmann** [comment]
I actually prefer the separate set of client classes.  Less confusion I think.  Decent trade-off vs. the re-use of existing classes IMO.

**Comment by carlesarnal** [comment]
> I actually prefer the separate set of client classes. Less confusion I think. Decent trade-off vs. the re-use of existing classes IMO.

Ok, let me take a look at any exception that I may be missing and I'll remove the draft status. Thanks!

**Comment by EricWittmann** [comment]
Also look at the test failures.

**Comment by carlesarnal** [comment]
Closed in favour of [this](https://github.com/Apicurio/apicurio-registry/pull/985).

**Pull request closed without merging**
