### PR TITLE
Set sensible defaults for Avro converter

### PR DESCRIPTION
**Pull request by alesj**
This PR is in reference to issue https://github.com/Apicurio/apicurio-registry/issues/378 - "Set sensible defaults for Avro converter".

### CODE REVIEW

**Comment by EricWittmann** [comment]
@gunnarmorling are there other defaults that are needed?

**Comment by gunnarmorling** [comment]
This was definitely the most pressing one. Other than that, it seems we're
configuring this all the time (for Avro *and* JSON):

    "value.converter.apicurio.registry.global-id" :
"io.apicurio.registry.utils.serde.strategy.AutoRegisterIdStrategy"

Not sure what the default behaviour for that one is right now; but for
Connect, I think we'd always want to have auto-registration if new/changed
schemas. So defaulting to that behaviour might make sense, too.

>

**Comment by alesj** [comment]
No, this one (AutoRegisterIdStrategy) always updates the schema (creates new version).

I guess we could add some new strategy, which caches current schemas,
and if none matches, then tries to find matching one server-side,
if that fails, create / update new.

**Comment by gunnarmorling** [comment]
> No, this one (AutoRegisterIdStrategy) always updates the schema (creates new version).

Oh, really? Didn't you show me one which did the caching already?
There definitely should be a notion of stability, i.e. if the same
schema is "registered" twice, it should keep the previously assigned
id.

**Comment by alesj** [comment]
We added one that created schema, if it didn't already exist.
Otherwise it will use existing.

Server-side we didn't want to add too many "smarts",
since comparing content can be costly; e.g. canonicalization, etc

I'll add the one I proposed, it should be optimal enough.

**Pull request merged**
