### PR TITLE
sql unit tests using postgresql, tests to reproduce sql search bug

### PR DESCRIPTION
**Pull request by famartinrh**
This adapts the sql module to run unit tests against postgresql using testcontainers...

During the process I found a bug in the sql search, but looks like only happens for postgresql.

The bug is with `SortBy.createdOn` and the error looks like 
```
Caused by: org.jdbi.v3.core.statement.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: COALESCE types timestamp without time zone and character varying cannot be matched
  Position: 307 [statement:"SELECT a.*, v.globalId, v.version, v.state, v.name, v.description, v.labels, v.properties, v.createdBy AS modifiedBy, v.createdOn AS modifiedOn FROM artifacts a JOIN versions v ON a.tenantId = v.tenantId AND a.latest = v.globalId WHERE a.tenantId = ? AND ((v.groupId = ?)) ORDER BY coalesce(v.createdOn, a.artifactId) asc LIMIT ? OFFSET ?", arguments:{positional:{0:_,1:4fb1925d-6612-4e54-9755-97c7316fd69c,2:20,3:0}, named:{}, finder:[]}]
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1794)
	at org.jdbi.v3.core.result.ResultProducers.lambda$getResultSet$2(ResultProducers.java:64)
	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:54)
	at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:228)
	at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:284)
	at org.jdbi.v3.core.result.ResultIterable.list(ResultIterable.java:273)
	at io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage.lambda$searchArtifacts$36(AbstractSqlRegistryStorage.java:1057)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:341)
	at io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage.withHandle(AbstractSqlRegistryStorage.java:146)
	... 189 more
Caused by: org.postgresql.util.PSQLException: ERROR: COALESCE types timestamp without time zone and character varying cannot be matched
  Position: 307
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at io.agroal.pool.wrapper.PreparedStatementWrapper.execute(PreparedStatementWrapper.java:297)
	at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1786)
	... 197 more

```
@EricWittmann wdyt would be the way to fix this?

### CODE REVIEW

**Comment by famartinrh** [comment]
ouch, it's not failing here as it was in my computer, maybe it was my fault. Integration tests should fail.

Also in the app module the new test `RegistryClientTest.testSearchArtifactSorByCreatedOn` shows another bug, the ordering returned is not correct.

**Comment by EricWittmann** [comment]
The problem with coalesce is probably new due to the new ability to order by fields other than artifactId/name.  The reason coalesce is used is because we wanted to order by artifact **name**, but use the **artifactId** in cases where the name is null.  So when ordering by **createdOn** we should drop the `coalesce()`.

The problem with ordering is not surprising, since each DB is a little different with regard to ordering by case I think.

**Comment by famartinrh** [comment]
the coalesce issue should be fixed, but the tests now show that the ordering is not consistent. The same test sometimes returns one ordering and sometimes other

**Comment by famartinrh** [comment]
@EricWittmann ok, everything is fixed now.

There were two bugs, one with `coalesce` and another was the rest client passing an incorrect query param for the orderby (which caused the wrong ordering)

**Comment by EricWittmann** [comment]
Nice changes.

**Pull request merged**
