### PR TITLE
Add schemaType to get schema by id response in compatibility layer

### PR DESCRIPTION
**Pull request by carlesarnal**

### CODE REVIEW

**Review by EricWittmann — APPROVED** [review]

**Comment by kmandal-volvo** [comment]
Which Apicurio version we will get the fix

**Comment by famartinrh** [comment]
I think the latest Apicurio Registry release in GitHub should already contain this commit

**Comment by carlesarnal** [comment]
This is also already published as images. Changes merged into master are always published as `latest-snapshot`. You just need to choose your storage variant, `mem`, `sql`, `kafkasql`.

**Comment by kmandal-volvo** [comment]
I am able to deploy using the below helm value hope this will give the output to address the issue. 
```
registry:
  enabled: true

  ## uncomment and adjust for kafka persistence
  # kafka:
  #   bootstrapServers: kafka1:9092,kafka2:9092

  ## uncomment and adjust for sql persistence
  sql:
    url: jdbc:postgresql://XXXX-pg.postgres.database.azure.com:XXXX/Apicurio_schema?sslmode=require
    username: XXXXXXX
    password: XXXXXXX

  image:
    registry: "quay.io"
    repository: "apicurio/apicurio-registry"
    tag: "2.0.1.Final"
 # list of name, value pairs of extra environment vars
#  extraEnv:
   
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 1300Mi
    # requests:
    #   cpu: 200m
    #   memory: 600Mi

sync:
  enabled: true
  image:
    registry: "quay.io"
    repository: "apicurio/apicurio-registry-kube-sync"
    tag: "latest-snapshot"
  # registryUrl:
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 800Mi
    # requests:
    #   cpu: 200m
    #   memory: 600Mi
```

**Comment by kmandal-volvo** [comment]
I receive the information and deployed it, let us check the fix after testing it.
https://github.com/Apicurio/apicurio-registry-content-sync-operator/issues/14

**Comment by EricWittmann** [comment]
Note: there is an official release out now you can use:  `2.1.0.Final`

**Pull request merged**
