### PR TITLE
Fix REST endpoint not following specification

### PR DESCRIPTION
**Pull request by jsenko**
Spec https://docs.confluent.io/current/schema-registry/develop/api.html#delete--subjects-(string-%20subject)-versions-(versionId-%20version)

### CODE REVIEW

**Comment by alesj** [comment]
@jsenko "delete" is not the only one that uses this "latest" version ... so you need to fix all of them ;-)
Perhaps abstract away this handling somehow, so we don't have all this copy-pasting ...

**Comment by jsenko** [comment]
Thanks, I'll check other endpoints

**Comment by EricWittmann** [comment]
@jsenko When you're done with the other endpoints can you resubmit this PR to `master`?  I performed the merge from `1.1.x` this morning so future PRs should no go onto `master` (FYI to @alesj and @smccarthy-ie as well)

**Comment by EricWittmann** [comment]
This can be closed, yes? @jsenko

**Pull request closed without merging**
