### PR TITLE
Allow for application.server override.

### PR DESCRIPTION
**Pull request by alesj**

### CODE REVIEW

**Comment by alesj** [comment]
@EricWittmann @Frawless we should test if this is necessary to run Registry in a cluster

**Comment by alesj** [comment]
@EricWittmann @Frawless yup, just confirmed, this is needed for a cluster setup -- at least in my docker-compose it was required --> it needed HOSTNAME:9000 config

We should also test on k8s / OpenShift.

**Comment by alesj** [comment]
See:
* https://github.com/alesj/registry-demo/blob/master/docker-registry.yaml#L12

**Comment by alesj** [comment]
This is whaty we'll probably need on k8s:

`
pod.spec.containers.env: 
  - name: APPLICATION_SERVER
    valueFrom: 
      fieldRef: metadata.name
`

**Comment by EricWittmann** [comment]
This is needed for -streams only?

**Comment by alesj** [comment]
Yes

**Pull request merged**
