### PR TITLE
Upgrade Quarkus to 1.9.0.CR1

### PR DESCRIPTION
**Pull request by alesj**

### CODE REVIEW

**Comment by EricWittmann** [comment]
Is there something in 1.9.0 that you need?

**Comment by alesj** [comment]
Not really, just trying to keep up with their changes / updates, so we
don’t get caught with too much fixes ... (as history tought us :-)

**Comment by EricWittmann** [comment]
OK fair enough.  :)  The JPA build is failing due to deprecated config properties which have been fixed on the SQL branch.

**Comment by alesj** [comment]
Ah ... that’s the only one storage type I didn’t test :-)
Ok, let me fix that and we can revisit this PR

**Comment by EricWittmann** [comment]
You'll see the error when you run the build - it's probably one of the most helpful errors I've seen in quite some time. :)  Kudos to the Quarkus team on that.

**Pull request merged**
