### PR TITLE
Fix links to REST API docs and cross references in Antora

### PR DESCRIPTION
**Pull request by smccarthy-ie**
Fixes links to auto-generated Registry REST API docs and internal cross references.

Adds local Antora playbook for testing (includes fix for broken x-refs)

Updates readme file with tips for contributing doc and latest Antora-based build steps

Adds stub doc files for new Registry Java client feature to make developer contribution easier

### CODE REVIEW

**Comment by EricWittmann** [comment]
@smccarthy-ie Can you point @carlesarnal to which asciidoc file he should edit to contribute the Rest client docs?

**Comment by EricWittmann** [comment]
I'm guessing it's ` docs/modules/ROOT/partials/getting-started/con-registry-client.adoc ` ?

**Comment by smccarthy-ie** [comment]
Hey @EricWittmann @carlesarnal, yes I've created the following stubs files:   

docs/modules/ROOT/partials/getting-started/con-registry-client.adoc 
docs/modules/ROOT/partials/getting-started/proc-registry-client.adoc 
docs/modules/ROOT/partials/getting-started/ref-registry-client.adoc

**Comment by smccarthy-ie** [comment]
@EricWittmann @carlesarnal And please see the updated readme in https://github.com/Apicurio/apicurio-registry/tree/master/docs

This explains the new directory structure and provides tips on how to add content. I've already created all the wireframe files that you need to get started documenting the new registry client, so you should be able to pour in your content :) 

Feel free to create any additional files as needed. I can tidy it all up later ;)  Thanks!

**Comment by EricWittmann** [comment]
Sweet, thanks @smccarthy-ie

**Comment by carlesarnal** [comment]
Thanks @smccarthy-ie!. @EricWittmann I'm going to create a new issue for the client documentation.

**Pull request merged**
