### PR TITLE
[Proposal] Split application properties into different files per profile

### PR DESCRIPTION
**Pull request by carlesarnal**
This is a proposal to extract the application properties to different files per profile. This should simplify our lives going forward whenever we need to add new properties from Quarkus itself or new features requiring properties to the application.

### CODE REVIEW

**Comment by EricWittmann** [comment]
Overall I like this.  One change though, can you use this plugin instead?

https://github.com/Apicurio/apicurio-common-app-components/tree/main/maven-plugin

I'd like to deprecate the one in registry.

**Comment by carlesarnal** [comment]
> Overall I like this. One change though, can you use this plugin instead?
> 
> https://github.com/Apicurio/apicurio-common-app-components/tree/main/maven-plugin
> 
> I'd like to deprecate the one in registry.

Done, I used this opportunity to also update the plugin used in the storage variants.

**Comment by EricWittmann** [comment]
@craicoverflow or @jsenko any objection to this?

**Comment by craicoverflow** [comment]
> @craicoverflow or @jsenko any objection to this?

No, it sounds like a nice improvement.

**Pull request merged**
