### PR TITLE
[MO] - [test] - set the enviroment for tests + smoke tests

### PR DESCRIPTION
**Pull request by Seequick1**
### Description
This PR just adding really simple test environment some smoke tests for the next work. 

### Type of change
- test 
- feature

### CODE REVIEW

**Comment by alesj** [comment]
Why do we duplicate tests?
We should somehow reuse the tests from app/test

And what's this smoteTest directory?
(some convention? or how are they found?)

**Comment by alesj** [comment]
Plus the tests should be generic -- no impl detail on the storage type.
e.g. that H2 service has been moved into jpa module, as it's a dependency of the JPA storage (it needs a database).

But that doesn't mean that the particular storage types / modules cannot have their own "custom" tests.

With all the others, we would like to re-use them on all existing storage types, hence the lack of impl details.

**Comment by Seequick1** [comment]
Well, this is just a starting point. That duplicates just have to serve as examples (smokes) in the test module.

**Comment by EricWittmann** [comment]
We can chat about this in tomorrow's meeting when we come up with a test plan, etc. :)

**Pull request closed without merging**
