### PR TITLE
don't run jobs when a workflow config is changed

### LINKED ISSUE #2313: Disable integration tests for changes that don't need them
I noticed when adding #2265 that the full suite of integration tests and other jobs executed when a file which would not affect these was changed.

These jobs can be resource intensive, and I think we should consider disabling workflows when they are not required to reduce carbon footprint.

### PR DESCRIPTION
**Pull request by craicoverflow**
Resolves #2313

### CODE REVIEW

**Comment by carlesarnal** [comment]
I disagree. With these changes, invalid changes to the workflows will be discovered only once merged into master. Is that what we want?

**Comment by craicoverflow** [comment]
Are the workflow files being validated in some of the jobs?

**Comment by carlesarnal** [comment]
Whenever a change is made to the workflow files, the job executed is the updated version, that's how they were being validated before.

**Comment by craicoverflow** [comment]
Ah yes that makes sense. So this should only have been added to `on.push.paths-ignore` then. Another option could be to use [dorny/paths-filter@v2](https://github.com/marketplace/actions/paths-changes-filter) to run each step conditionally. Which would you prefer?

**Comment by carlesarnal** [comment]
I think step 1 can be to use `on.push.paths-ignore,` to restore the old behaviour and then we can implement more steps like this to improve the execution of the jobs (I'm actually working on some things around CI jobs). I'll create a PR restoring the old behaviour and we can continue from there.

**Pull request merged**
