### PR TITLE
fix: redirect configuration

### PR DESCRIPTION
**Pull request by jsenko**

### CODE REVIEW

**Comment by EricWittmann** [comment]
@jsenko this is breaking the IBM compat test, interestingly.  It's not a transient error.  WDYT?

**Comment by jsenko** [comment]
Just a quick guess, IBM API is by default disabled and is being enabled during the tests. It's possible the disable filter does not work properly.

**Comment by jsenko** [comment]
This is the error:
```
java.lang.IllegalStateException: UT010026: Async is not supported for this request, as not all filters or Servlets were marked as supporting async
```
The IBM API uses async processing which the servlet filters must be configured to support.

**Comment by jsenko** [comment]
The previous test failure was caused by an error in the `CheckPeriodCache`:
```
java.lang.IllegalStateException: Recursive update
 at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1991)
 at io.apicurio.registry.utils.CheckPeriodCache.compute(CheckPeriodCache.java:36)
 at io.apicurio.registry.mt.TenantContextLoader.loadRequestContext(TenantContextLoader.java:81)
 at io.apicurio.registry.mt.TenantContextLoader_ClientProxy.loadRequestContext(Unknown Source)
 at io.apicurio.registry.mt.TenantContextImpl.lambda$load$1(TenantContextImpl.java:69)
 at java.base/java.util.Optional.map(Optional.java:260)
 at io.apicurio.registry.mt.TenantContextImpl.load(TenantContextImpl.java:69)
```
Since I was fixing that, I also decided to add eviction:) Should I add the `threshold` as a config parameter?

**Review by EricWittmann — APPROVED** [review]
Nice changes, thanks.

**Pull request merged**
