### PR TITLE
Support for MySQL storage

### PR DESCRIPTION
**Pull request by Yoni-Weisberg**
pull request for https://github.com/Apicurio/apicurio-registry/issues/5309

### CODE REVIEW

**Review by EricWittmann — APPROVED** [review]
This looks pretty good to me!  I'd like to get at least one more review before merging.  @carlesarnal or @jsenko ?

**Comment by EricWittmann** [comment]
@Yoni-Weisberg can you please run `mvn spotless:apply` and then commit the resulting changes?

**Comment by carlesarnal** [comment]
> @Yoni-Weisberg can you please run `mvn spotless:apply` and then commit the resulting changes?



> This looks pretty good to me! I'd like to get at least one more review before merging. @carlesarnal or @jsenko ?

I though I already approved it but I just approved the CI execution. I'll wait until CI is green for the final +1.

**Comment by Yoni-Weisberg** [comment]
Hi @carlesarnal, I've run spotless. waiting for CI workflow again

**Review by EricWittmann — APPROVED** [review]

**Review by carlesarnal — APPROVED** [review]

**Comment by EricWittmann** [comment]
Nice work, thanks for the contribution @Yoni-Weisberg

**Pull request merged**
