### PR TITLE
Remove multitenancy

### PR DESCRIPTION
**Pull request by carlesarnal**
This PR removes all the bits related to multitenancy. 

To be able to do it, the automatic upgrade process is removed as well, since removing multitenancy is a breaking change from a data structure perspective. Therefore, all the upgrade scripts have been removed as well since once this is merged the only way to migrate the data will be the import/export feature. This raises the question of whether to restart the database version number since all the installations using version 3 will be fresh installations without the old automatic database structure migration process. I decided to reset it in this PR, but that can be reverted very easily.

### CODE REVIEW

**Review by jsenko — CHANGES_REQUESTED** [review]
LGTM after the workflow succeeds

**Review by EricWittmann — DISMISSED** [review]

**Comment by pantaoran** [comment]
I'm confused, why is multitenancy being removed? Will this no longer be a feature?
I mean, it was actually never really a feature since it was never really documented. However, I want to have some authorization features, and since I have an API Gateway in front of Apicurio which takes care of authentication, multitenancy looked very promising.
Should I abort my efforts to get MT to work, since it will be removed in v3?

**Comment by EricWittmann** [comment]
I responded to this in an old discussion thread as well but happy to respond here as well. 

Yes, in 3.0 we have removed the multi-tenant feature.  The reason for this is that we didn't have any community desire for it, and the Red hat product that required it was decommissioned. 

That said, if there is a community need we could revisit and re-implement. 

If your need is more authorization based, I think we might prefer to collaborate on that rather than reintroduce multitenancy. Could you open a new GitHub issue or discussion thread on this topic? Perhaps you can explain your specific use case and we can see what we can do. We know that our authorization story needs to be better than it is.

**Comment by pantaoran** [comment]
Thank you very much for your reply. Your confirmation saves me the time of getting MT to work in the 2.x versions, knowing now that it will never be officially available.

I have therefore created https://github.com/Apicurio/apicurio-registry/issues/5125 to detail my needs.

**Pull request merged**
