### PR TITLE
Antora layout

### PR DESCRIPTION
**Pull request by pwright**
* change file layout to antora style
* fix symlinks for downstream docs
* show possible link method for upstream/downstream

@smccarthy-ie  here's the proposed structure

### CODE REVIEW

**Comment by smccarthy-ie** [comment]
Thanks @pwright, the new layout looks good!

**Comment by EricWittmann** [comment]
Should I go ahead and merge this?

**Comment by pwright** [comment]
@EricWittmann let's wait for a review from @smccarthy-ie

**Comment by smccarthy-ie** [comment]
@EricWittmann @pwright I've built this using antora locally and the new layout and navigation looks good, a lot less overwhelming than before. Thanks Paul! 

There are some issues that we can fix in subsequent PRs (e.g., "Edit this Page" feature, readme content, links to REST API docs). But I'd suggest merging this to improve the layout, which was the biggest issue we had. Thanks.

**Comment by EricWittmann** [comment]
I've also built this locally, and using the playbook I have here:  https://github.com/Apicurio/apicurio-docs-playbook

I'm going to delete the playbook inside the /docs directory to avoid confusion.

**Pull request merged**
