### PR TITLE
Backport of PR#5052

### LINKED ISSUE #4965: Understanding the FULL compatibility of APICURIO
hey folks! Feeling a bit stupid here and need your help! 🙏 

I have been playing with APICURIO lately, especially if I enable `FULL` compatibility as a global rule.

I'm using Json type `req.Header.Set("X-Registry-ArtifactType", "JSON")`

Then add a new schema like this:

```json
{
  "type": "object",
  "properties": {
    "foo": { "type": "string" }
  },
  "required":["foo"],
  "additionalProperties": { "type": "string" }
}
```

Then if I try to update it I call the create endpoint with `?ifExists=RETURN_OR_UPDATE&canonical=true` with a new version of the schema like this:

```json
{
  "type": "object",
  "properties": {
    "foo": { "type": "string" },
    "bar": { "type": "string" }
  },
  "required":["foo"],
  "additionalProperties": { "type": "string" }
}
```

Isn't this considered a full compatible version?
**If not,** then what it is?
**If yes,** then why i get `OBJECT_TYPE_PROPERTY_SCHEMAS_NARROWED` error?

even if i try with:
```json
{
  "type": "object",
  "properties": {
    "foo": { "type": "string" }
  },
  "required":["foo"]
}
```
then
```json
{
  "type": "object",
  "properties": {
    "foo": { "type": "string" },
    "bar":{ "type": "string" }
  },
  "required":["foo"]
}
```

> I'm using `registry.hub.docker.com/apicurio/apicurio-registry-mysql:2.6.x-release`

<details>
   <summary>APICURIO Logs</summary>
   <pre>
     2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-187) Selecting artifact (latest version) meta-data: testing test-record2 (behavior = SKIP_DISABLED_LATEST)
2024-08-02 07:49:21 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-187) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-08-02 07:49:21 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-187) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-08-02 07:49:21 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-187) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-08-02 07:49:21 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-187) Datasource '<default>': JDBC resources leaked: 2 ResultSet(s) and 0 Statement(s)
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-187) Inserting an artifact row for: testing test-record2
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.metrics.health.liveness.LivenessUtil] (executor-thread-187) Ignored intercepted exception: io.apicurio.registry.storage.ArtifactAlreadyExistsException :: An artifact with ID 'test-record2' in group 'testing' already exists.
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.metrics.health.liveness.LivenessUtil] (executor-thread-187) Ignored intercepted exception: io.apicurio.registry.storage.ArtifactAlreadyExistsException :: An artifact with ID 'test-record2' in group 'testing' already exists.
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.metrics.health.liveness.LivenessUtil] (executor-thread-187) Ignored intercepted exception: io.apicurio.registry.storage.ArtifactAlreadyExistsException :: An artifact with ID 'test-record2' in group 'testing' already exists.
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-187) Selecting artifact (latest version) meta-data: testing test-record2 (behavior = SKIP_DISABLED_LATEST)
2024-08-02 07:49:21 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-187) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-187) Selecting artifact (latest version) meta-data: testing test-record2 (behavior = DEFAULT)
2024-08-02 07:49:21 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-187) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-08-02 07:49:21 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-187) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.metrics.health.liveness.LivenessUtil] (executor-thread-187) Ignored intercepted exception: io.apicurio.registry.storage.ArtifactNotFoundException :: No artifact with ID 'test-record2' in group 'testing' was found.
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-187) Selecting artifact (latest version) meta-data: testing test-record2 (behavior = SKIP_DISABLED_LATEST)
2024-08-02 07:49:21 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-187) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (executor-thread-187) Getting a list of all artifact rules for: testing test-record2
2024-08-02 07:49:21 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-187) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-08-02 07:49:21 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-187) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-08-02 07:49:21 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-187) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-08-02 07:49:21 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-187) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-08-02 07:49:21 WARN <_> [io.quarkus.agroal.runtime.AgroalEventLoggingListener] (executor-thread-187) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.rules.compatibility.jsonschema.diff.DiffContext] (executor-thread-187) [Context path (updated): ]Visiting ObjectSchemaWrapper(wrapped={"type":"object","required":["foo"],"properties":{"bar":{"type":"string"},"foo":{"type":"string"}}}) at #
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.rules.compatibility.jsonschema.diff.DiffContext] (executor-thread-187) [Context path (updated): /properties/foo]Visiting StringSchemaWrapper(wrapped={"type":"string"}) at #/properties/foo
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.rules.compatibility.jsonschema.diff.DiffContext] (executor-thread-187) [Context path (updated): /properties/foo]Visiting formatValidator unnamed-format
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.rules.compatibility.jsonschema.diff.DiffContext] (executor-thread-187) [Context path (updated): ]Visiting ObjectSchemaWrapper(wrapped={"type":"object","required":["foo"],"properties":{"foo":{"type":"string"}}}) at #
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.rules.compatibility.jsonschema.diff.DiffContext] (executor-thread-187) [Context path (updated): /properties/foo]Visiting StringSchemaWrapper(wrapped={"type":"string"}) at #/properties/foo
2024-08-02 07:49:21 DEBUG <_> [io.apicurio.registry.rules.compatibility.jsonschema.diff.DiffContext] (executor-thread-187) [Context path (updated): /properties/foo]Visiting formatValidator unnamed-format
2024-08-02 07:49:21 INFO <_> [io.apicurio.common.apps.logging.audit.AuditLogService] (executor-thread-187) apicurio.audit action="createArtifact" result="failure" src_ip="172.18.0.5" if_exists="RETURN_OR_UPDATE" artifact_type="JSON" error_msg="Incompatible artifact: test-record2 [JSON], num of incompatible diffs: {1}, list of diff types: [OBJECT_TYPE_PROPERTY_SCHEMAS_NARROWED at /propertySchemasAdded] Causes: OBJECT_TYPE_PROPERTY_SCHEMAS_NARROWED at /propertySchemasAdded" group_id="testing" name="test-record2" canonical="true" artifact_id="test-record2" version="1.1.0"
   </pre>
</details>

Thanks

### PR DESCRIPTION
**Pull request by jsenko**
Backport of [fix: JSON Schema compat: Removing object property/array item does not take additional properties/items into account ](https://github.com/Apicurio/apicurio-registry/pull/5052)

Fixes #4965

### CODE REVIEW

**Comment by AhmedRaafat14** [comment]
Hey @jsenko ,

Sorry for continuous DM from me, I was checking the latest image and it is not published yet I see a workflow failure here: https://github.com/Apicurio/apicurio-registry/actions?query=branch%3A2.6.x+

Thanks

**Comment by jsenko** [comment]
Which image have you used? Until we do a next release, you can try the snapshot image e.g. `quay.io/apicurio/apicurio-registry-mem:2.6.x-snapshot`.

**Comment by AhmedRaafat14** [comment]
I'm using the `mysql` image: `registry.hub.docker.com/apicurio/apicurio-registry-mysql:2.6.x-release`

**Comment by AhmedRaafat14** [comment]
Are there any plans to update this image soon?

https://hub.docker.com/r/apicurio/apicurio-registry-mysql/tags

**Pull request merged**
