### PR TITLE
fix: JSON Schema compat: Removing object property/array item does not take additional properties/items into account

### PR DESCRIPTION
**Pull request by jsenko**
Fixes [#4965](https://github.com/Apicurio/apicurio-registry/issues/4965)

### CODE REVIEW

**Comment by jsenko** [comment]
Please check that this fixes your issue @AhmedRaafat14

**Comment by AhmedRaafat14** [comment]
> Please check that this fixes your issue @AhmedRaafat14

@jsenko this does it indeed, thanks a lot!

**Review by AhmedRaafat14 — APPROVED** [review]

**Review by EricWittmann — APPROVED** [review]

**Comment by AhmedRaafat14** [comment]
hey @jsenko !

When can I expect to have a new tag for this image: https://hub.docker.com/r/apicurio/apicurio-registry-mysql/tags ?

Thanks

**Comment by AhmedRaafat14** [comment]
hey @jsenko !

When can I expect to have a new tag for this image: https://hub.docker.com/r/apicurio/apicurio-registry-mysql/tags ?

I saw the actions didn't have update MySQL docker image: https://github.com/Apicurio/apicurio-registry/actions/runs/10474189624/job/29008623072

Thanks

**Pull request merged**
