### PR TITLE
Update to Quarkus 1.3.0.Alpha1

### PR DESCRIPTION
**Pull request by rsvoboda**
Update to Quarkus 1.3.0.Alpha1

`mvn clean verify` worked well on my machine

### CODE REVIEW

**Comment by EricWittmann** [comment]
We need to make sure we use the appropriate version of Quarkus given our release schedule in about a month.  I'll check on that before we merge this.

**Comment by rsvoboda** [comment]
@gsmet / @sanne / @stuartwdouglas
apicurio-registry build has troubles to do simple jump to Quarkus 1.3.0.Alpha1.

First issue is related to Hibernate, but the can be more.

To replicate just clone the repo and run `./mvnw -Pjpa test package -Dquarkus.version=1.3.0.Alpha1`

```
[error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#build 
  threw an exception: io.quarkus.deployment.configuration.ConfigurationError: 
  Hibernate extension cannot guess the dialect as no JDBC driver is specified
  by 'quarkus.datasource.driver'
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.guessDialect(HibernateOrmProcessor.java:715)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.handleHibernateORMWithNoPersistenceXml(HibernateOrmProcessor.java:557)
	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.build(HibernateOrmProcessor.java:199)
```

**Comment by Sanne** [comment]
I think it's relating to https://github.com/quarkusio/quarkus/issues/7065 , which was fixed already. Could you test `master` ?

**Comment by stuartwdouglas** [comment]
I just tested this against Quarkus master and it passed

**Comment by rsvoboda** [comment]
Closing as newer version is needed.

**Comment by stuartwdouglas** [comment]
The workaround is to use %test. properties in your main application.properties.

**Pull request closed without merging**
