### PR TITLE
Add a test to validate an openapi artifact

### PR DESCRIPTION
**Pull request by EricWittmann**
This is primarily to ensure that openapi validation works in native builds.

### CODE REVIEW

**Comment by andreaTP** [comment]
Re-running the CI jobs as the failure looks spurious.

**Comment by EricWittmann** [comment]
Hrm - I expected this to fail in the native image tests without your fix @andreaTP .  I wonder if our native image build isn't running the Quarkus tests against the native images?

**Comment by EricWittmann** [comment]
Ah it seems it's running **some** of our tests against the native images but not all of them.  I'll need to revisit.

**Comment by EricWittmann** [comment]
I'm going to close this as not relevant.  We'll need to create a test in one of the integration test suites for this to make sense.  @obabec WDYT?

**Pull request closed without merging**
