### PR TITLE
Add ability to provide additional headers issue 827

### PR DESCRIPTION
**Pull request by tagarr**
Add additional headers to registry client via config

Signed-off-by: A. Garrard <GARRARD@uk.ibm.com>

### CODE REVIEW

**Review by carlesarnal — APPROVED** [review]
LGTM. But, please, note that the `CompatibleClient` that you're modifying is deprecated and you should use the `RegistryRestClient` that already have the headers addition capability.

**Comment by tagarr** [comment]
Thanks, duly noted

**Review by EricWittmann — APPROVED** [review]

**Comment by EricWittmann** [comment]
@carlesarnal I think your client docs mentioned something about custom headers but I'm not sure whether it was specific enough about how exactly to do that.  What do you think?

**Comment by carlesarnal** [comment]
> @carlesarnal I think your client docs mentioned something about custom headers but I'm not sure whether it was specific enough about how exactly to do that. What do you think?

Maybe I should be a bit more specific, let me expand it the docs.

**Comment by carlesarnal** [comment]
Documented by [955](https://github.com/Apicurio/apicurio-registry/pull/955)

**Pull request merged**
