### PR TITLE
Add wildcard content type

### PR DESCRIPTION
**Pull request by carlesarnal**

### CODE REVIEW

**Comment by EricWittmann** [comment]
@Apicurio/ibm-developers What do you think about this as a default?  We'll also look at how to enable overriding of the content type dynamically.

@carlesarnal We'll need to test whether setting `Content-Type` as a header via the `HeadersInterceptor` actually overrides what is provided by `RequestBody.create(MediaType.parse("*/*")` right?

**Review by EricWittmann — APPROVED** [review]
Looks like a good default until we can support dynamic headers.

**Comment by tagarr** [comment]
Works for me

**Comment by EricWittmann** [comment]
Is there a GitHub Issue related to this?  If there is, please close it. 👍

**Pull request merged**
