### PR TITLE
Fix complex array validation when field is not present

### PR DESCRIPTION
**Pull request by carlesarnal**

### CODE REVIEW

**Review by EricWittmann — APPROVED** [review]

**Comment by Gourav2912** [comment]
Request for a release 2.3.2 to test fix.

**Comment by carlesarnal** [comment]
@Gourav2912 there is no need for a release, you can test the fix using the tag `latest-snapshot`. If we confirm it as fixed, then we can do a new release including not only that fix but also other useful stuff.

**Comment by Gourav2912** [comment]
Hello @carlesarnal @EricWittmann Fix is working now as expected. Thanks for fix. It will be great help if u can release this ASAP , so we can integrate and deploy in our PROD

**Comment by Gourav2912** [comment]
Please consider above request for release

**Comment by Gourav2912** [comment]
@carlesarnal @EricWittmann Is there any release plan including  this change soon?

**Comment by Gourav2912** [comment]
Hello @carlesarnal  Request you to please let us know plan for next release , as we are able to use this fix and which causing issue for us in PROD. Please release fix ASAP ..

**Pull request merged**
