### PR TITLE
Create Test BOM for storage modules to share

### PR DESCRIPTION
**Pull request by riprasad**

### CODE REVIEW

**Comment by EricWittmann** [comment]
I think this is on the right track, but the build is failing. :)  The goal is exactly right - we want to isolate the test dependencies somewhere, and having them in the parent makes sense.  We just need to make sure the build still works!  In the current failure, it looks like the H2 database is not being started up for the SQL storage module tests.  There is some sort of test service that is responsible for this called `H2DatabaseService` which I'm assuming is not being run anymore.

**Comment by riprasad** [comment]
Glad to know that the changes are in the right direction. Regarding test failures, I've already reached out to @famartinrh for some help. Hopefully, we'll have a successful build today

**Comment by riprasad** [comment]
Also, kafkasql and streams storage modules have a couple of test dependencies specific to themselves. I've not included them in the parent and only pulled out test dependencies that are common to all the modules.

**Comment by famartinrh** [comment]
this is the error I see
```
2021-03-10T14:06:17.8290370Z 2021-03-10 14:06:17,210 ERROR [io.api.reg.sto.uti.H2DatabaseService] (H2-thread) H2 err > Error: Could not find or load main class org.h2.tools.Server
2021-03-10T14:06:17.8298889Z 2021-03-10 14:06:17,211 ERROR [io.api.reg.sto.uti.H2DatabaseService] (H2-thread) H2 err > Caused by: java.lang.ClassNotFoundException: org.h2.tools.Server
2021-03-10T14:06:17.8311590Z 2021-03-10 14:06:17,240 ERROR [io.api.reg.sto.uti.H2DatabaseService] (H2-thread) H2 Server process exited with error: 1, msgs: [e: Error: Could not find or load main class org.h2.tools.Server, e: Caused by: java.lang.ClassNotFoundException: org.h2.tools.Server]
2021-03-10T14:06:19.7351751Z 2021-03-10 14:06:19,732 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Connection is broken: "java.net.ConnectException: Connection refused (Connection refused): localhost:9123" [90067-197]
```

However I don't understand why your changes affected to this

**Comment by EricWittmann** [comment]
@riprasad Can you try this again now with the latest from `master`?

**Pull request closed without merging**
