### PR TITLE
Feat/artifact groups test old serdes release

### PR DESCRIPTION
**Pull request by famartinrh**
This makes the legacy testsuite tests the client and serdes released with the `1.3.2.Final` release to verify the compatibility with the v1 API we are now exposing.

In order for our  actual v1 API to be compatible I had to revert the changes in PR #1132 , but only in the context of the v1 API. 
**Dates will continue to be in the proper format for the v2 API!**

After this we are free to remove from the codebase the "old" serdes and the `apicurio-registry-rest-client`

### CODE REVIEW

**Comment by EricWittmann** [comment]
@carlesarnal FYI the date change you made to fix the ISO8601 format problem with the API was reverted, but only for the V1 API.  Can you verify that the V2 API works as desired with ISO8601 formatted dates?

**Review by EricWittmann — APPROVED** [review]

**Comment by EricWittmann** [comment]
This is great - good validation that our old 1.3.2 client and serdes will continue to work against the new server.

**Comment by carlesarnal** [comment]
> @carlesarnal FYI the date change you made to fix the ISO8601 format problem with the API was reverted, but only for the V1 API. Can you verify that the V2 API works as desired with ISO8601 formatted dates?

Hi @EricWittmann, the date format for the V2 is not the expected one. We're missing a part of the annotation for the API to return a proper ISO8601 formatted date. I'll open a separate PR fixing the problem.

**Comment by carlesarnal** [comment]
PR created #1231.

**Pull request merged**
