### PR TITLE
fix - tests not executed

### PR DESCRIPTION
**Pull request by famartinrh**

### CODE REVIEW

**Comment by famartinrh** [comment]
In the integration tests run can be seen that tests that use @RegistryServiceTest are not executed, it smells like an issue where the extension registered in that annotation is not picked, and this could happen because of the recent update of Junit that updating quarkus brought

```
2020-06-16T11:05:09.9465638Z 2020-06-16 11:05:09 INFO [TestSeparator:34] ############################################################################
2020-06-16T11:05:09.9466651Z 2020-06-16 11:05:09 INFO [TestSeparator:35] io.apicurio.tests.smokeTests.confluent.MetadataConfluentIT.getAndUpdateMetadataOfSchema-STARTED
2020-06-16T11:05:10.1286276Z 2020-06-16 11:05:10 INFO [BaseIT:57] Checking that created schema is equal to the get schema
2020-06-16T11:05:10.1675718Z 2020-06-16 11:05:10 INFO [BaseIT:60] Created schema with id:1 and name:myrecord1
2020-06-16T11:05:10.1856062Z 2020-06-16 11:05:10 INFO [MetadataConfluentIT:51] Scheme name: myrecord1 has following metadata: {"type":"record","name":"myrecord1","fields":[{"name":"foo","type":"string"}]}
2020-06-16T11:05:10.1971366Z 2020-06-16 11:05:10 INFO [BaseIT:72] Deleting confluent schema 7af33c60-1e72-44fd-a81c-e834f0f99cad
2020-06-16T11:05:10.2146764Z 2020-06-16 11:05:10 INFO [BaseIT:103] Removing all artifacts
2020-06-16T11:05:10.2427160Z 2020-06-16 11:05:10 INFO [TestSeparator:40] io.apicurio.tests.smokeTests.confluent.MetadataConfluentIT.getAndUpdateMetadataOfSchema-FINISHED
2020-06-16T11:05:10.2434632Z 2020-06-16 11:05:10 INFO [TestSeparator:41] ############################################################################
2020-06-16T11:05:13.2605828Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.612 s - in io.apicurio.tests.smokeTests.confluent.MetadataConfluentIT
2020-06-16T11:05:13.2663663Z [INFO] Running io.apicurio.tests.smokeTests.apicurio.ArtifactsIT
2020-06-16T11:05:13.2664510Z 2020-06-16 11:05:13 INFO [RegistryFacade:39] Starting Registry Facade
2020-06-16T11:05:13.2728279Z 2020-06-16 11:05:13 INFO [TestUtils:114] Trying to connect to localhost:8081
2020-06-16T11:05:13.2732617Z 2020-06-16 11:05:13 WARN [TestUtils:119] Cannot connect to Registry instance: Connection refused (Connection refused)
2020-06-16T11:05:13.2784123Z 2020-06-16 11:05:13 INFO [RegistryFacade:43] Checking runner JAR path (1): ../app/target/apicurio-registry-app-1.2.3-SNAPSHOT-runner.jar
2020-06-16T11:05:13.2787196Z 2020-06-16 11:05:13 INFO [RegistryFacade:60] Starting Registry app from: ../app/target/apicurio-registry-app-1.2.3-SNAPSHOT-runner.jar
2020-06-16T11:05:14.2739593Z 2020-06-16 11:05:14 INFO [TestUtils:114] Trying to connect to localhost:8081
2020-06-16T11:05:14.2744093Z 2020-06-16 11:05:14 WARN [TestUtils:119] Cannot connect to Registry instance: Connection refused (Connection refused)
2020-06-16T11:05:15.2824833Z 2020-06-16 11:05:15 INFO [TestUtils:114] Trying to connect to localhost:8081
2020-06-16T11:05:15.2825403Z 2020-06-16 11:05:15 WARN [TestUtils:119] Cannot connect to Registry instance: Connection refused (Connection refused)
2020-06-16T11:05:16.2845153Z 2020-06-16 11:05:16 INFO [TestUtils:114] Trying to connect to localhost:8081
2020-06-16T11:05:16.2846520Z 2020-06-16 11:05:16 INFO [TestUtils:116] Client is able to connect to Registry instance
2020-06-16T11:05:16.4597823Z 2020-06-16 11:05:16 INFO [TestUtils:134] Service registry is ready
2020-06-16T11:05:16.4598713Z 2020-06-16 11:05:16 INFO [BaseIT:87] Registry app is running on http://localhost:8081/api
2020-06-16T11:05:19.4829732Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.206 s - in io.apicurio.tests.smokeTests.apicurio.ArtifactsIT
```

**Comment by EricWittmann** [comment]
Do you need this merged or is it enough to see the output from the workflows run against this PR?

**Comment by famartinrh** [comment]
no need to merge this, the output from this PRs workflows is the only usefull thing
btw, I need help to figure out what is going on with this

**Comment by famartinrh** [comment]
@EricWittmann if this works I would like to merge it

**Comment by famartinrh** [comment]
@EricWittmann it worked perfectly

**Pull request merged**
