### PR TITLE
Improve rest client logging

### PR DESCRIPTION
**Pull request by carlesarnal**

### CODE REVIEW

**Comment by famartinrh** [comment]
logging for client side libraries have to be treated carefully, I'm not sure if this changes may make logging output too verbose for some users

it may be interesting to know @jcechace opinion

**Comment by carlesarnal** [comment]
> logging for client side libraries have to be treated carefully, I'm not sure if this changes may make logging output too verbose for some users
> 
> it may be interesting to know @jcechace opinion

That’s the exact reason why I’m using debug. IMO (known) exceptions thrown by the client must be handled by the application using the client. This just adds additional info to the log in case is needed.

**Comment by EricWittmann** [comment]
What is the reason for switching to SLF 4J rather than Java util?

**Comment by carlesarnal** [comment]
> What is the reason for switching to SLF 4J rather than Java util?

No reason other than consistency. We're using slf4j in the application itself so I think it's better for consistency.

**Comment by EricWittmann** [comment]
Consistency is generally a good thing, I agree - although in this case it introduces another dependency.   It seems like for the REST client we might want to minimize those.

**Comment by EricWittmann** [comment]
WDYT?  ^^^

**Comment by carlesarnal** [comment]
Sorry, missed this one in my GitHub email. I usually would agree with you in dependencies relate to the rest client but I think slf4j is light and valuable enough to be worth adding it. That said, this is not a strong opinion but a biased one due to my personal experience with slf4j.

**Comment by EricWittmann** [comment]
In that case I'm fine with merging this.  Can you fix the conflict(s)?  :)  Then let me know and I'll merge!

**Comment by carlesarnal** [comment]
Done, we can merge this now.

**Pull request merged**
