### PR TITLE
fix: Handle export of v1 artifacts in DISABLED state

### PR DESCRIPTION
**Pull request by ajborley**
- Retrieving the content of artifacts in DISABLED state from Apicurio
 Registry v1.x returns a 404 Not Found response. This commit allows the
 exportV1 tool to handle artifacts in DISABLED state by not attempting
 to retrieve their content and only writing the metadata to the output
 zip file.
 - When the zip file is supplied to the v2 `/admin/import` endpoint, a
 `Failed to import content entity` message and `RuntimeSqlException`
 stacktrace is seen in the logs but all other artifacts are correctly
 imported.

Signed-off-by: Andrew Borley <borley@uk.ibm.com>

### CODE REVIEW

**Comment by famartinrh** [comment]
super nice, thank you! @ajborley can you describe in more detail why when importing a
`Failed to import content entity` message and `RuntimeSqlException`
stacktrace is seen in the logs but all other artifacts are correctly
imported?

**Comment by ajborley** [comment]
> can you describe in more detail why when importing a
Failed to import content entity message and RuntimeSqlException
stacktrace is seen in the logs but all other artifacts are correctly
imported?

Sure - I have a 1.3.2 Apicurio registry which contains an artifact with 3 versions, of which version 2 is in DISABLED state.
When I run the exportV1 tool with this update, I get a registry-export.zip with the following contents:
```
Archive:  registry-export.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      224  11-16-2021 15:36   manifest-2021-11-16T15:36:24.410Z.Manifest.json
      179  11-16-2021 15:36   content/3d690f2494d6069311f63714e4ce07770c5830f9165d9692740e5c4df3d83168.Content.json
      618  11-16-2021 15:36   content/3d690f2494d6069311f63714e4ce07770c5830f9165d9692740e5c4df3d83168.Content.data
      287  11-16-2021 15:36   groups/default/artifacts/aircraft_schema/versions/1.ArtifactVersion.json
      184  11-16-2021 15:36   content/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.Content.json
        0  11-16-2021 15:36   content/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.Content.data
      275  11-16-2021 15:36   groups/default/artifacts/aircraft_schema/versions/2.ArtifactVersion.json
      184  11-16-2021 15:36   content/39f83fa934b190238f60268999b8d19e45ed6dc06593c48565adb7f141ba0d1f.Content.json
      709  11-16-2021 15:36   content/39f83fa934b190238f60268999b8d19e45ed6dc06593c48565adb7f141ba0d1f.Content.data
      273  11-16-2021 15:36   groups/default/artifacts/aircraft_schema/versions/3.ArtifactVersion.json
       46  11-16-2021 15:36   rules/VALIDITY.GlobalRule.json
       51  11-16-2021 15:36   rules/COMPATIBILITY.GlobalRule.json
---------                     -------
     3030                     12 files
```

As you can see, the content/xxx.Content.data entry for version 2 has size 0. Without the fix in this PR the exportV1 tool fails and stops when it tries to retrieve the content for version 2.

When I subsequently call the `/admin/import` endpoint of a 2.1.0.Final Apicurio registry with the above registry-export.zip, e.g:
```
curl  http://localhost:8080/admin/import \
  -H "Accept: application/json" \
  -H "Content-Type: application/zip" \
  --data-binary @./registry-export.zip
```
It accepts the file and returns 204 No Content. In the registry logs I see the following output:

```
2021-11-321 14:39:28 INFO <_> [io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage] (executor-thread-1) ---------- Import Info ----------
2021-11-321 14:39:28 INFO <_> [io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage] (executor-thread-1) System Name:    Remote Registry
2021-11-321 14:39:28 INFO <_> [io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage] (executor-thread-1) System Desc:    Unknown remote registry (export created using v1 export utility).
2021-11-321 14:39:28 INFO <_> [io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage] (executor-thread-1) System Version: n/a
2021-11-321 14:39:28 INFO <_> [io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage] (executor-thread-1) Data exported on Tue Nov 16 15:36:24 GMT 2021 by user export-utility-v1
2021-11-321 14:39:28 INFO <_> [io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage] (executor-thread-1) ---------- ----------- ----------
2021-11-321 14:39:28 INFO <> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Content entity imported successfully.
2021-11-321 14:39:28 INFO <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Artifact created successfully.
2021-11-321 14:39:28 INFO <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Content entity imported successfully.
2021-11-321 14:39:29 WARN <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Failed to import content entity.: io.apicurio.registry.storage.impl.sql.jdb.RuntimeSqlException: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "FK_VERSIONS_2: PUBLIC.VERSIONS FOREIGN KEY(CONTENTID) REFERENCES PUBLIC.CONTENT(CONTENTID) (131072)"; SQL statement:
INSERT INTO versions (globalId, tenantId, groupId, artifactId, version, versionId, state, name, description, createdBy, createdOn, labels, properties, contentId) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23506-197]
	at io.apicurio.registry.storage.impl.sql.jdb.UpdateImpl.execute(UpdateImpl.java:46)
	at io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage.importArtifactVersion(AbstractSqlRegistryStorage.java:2622)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore.lambda$importArtifactVersion$9(KafkaSqlStore.java:184)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore$$Lambda$752/0x000000001c226580.withHandle(Unknown Source)
	at io.apicurio.registry.storage.impl.sql.HandleFactory.withHandle(HandleFactory.java:44)
	at io.apicurio.registry.storage.impl.sql.HandleFactory.withHandleNoException(HandleFactory.java:52)
	at io.apicurio.registry.storage.impl.sql.HandleFactory_ClientProxy.withHandleNoException(HandleFactory_ClientProxy.zig:129)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore.importArtifactVersion(KafkaSqlStore.java:183)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_Subclass.importArtifactVersion$$superaccessor17(KafkaSqlStore_Subclass.zig:9758)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_Subclass$$function$$17.apply(KafkaSqlStore_Subclass$$function$$17.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.apicurio.registry.logging.LoggingInterceptor.logMethodEntry(LoggingInterceptor.java:55)
	at io.apicurio.registry.logging.LoggingInterceptor_Bean.intercept(LoggingInterceptor_Bean.zig:327)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:127)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_Subclass.importArtifactVersion(KafkaSqlStore_Subclass.zig:9715)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_ClientProxy.importArtifactVersion(KafkaSqlStore_ClientProxy.zig:766)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink.processArtifactMessage(KafkaSqlSink.java:281)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink.doProcessMessage(KafkaSqlSink.java:152)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink.processMessage(KafkaSqlSink.java:104)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink_Subclass.processMessage$$superaccessor1(KafkaSqlSink_Subclass.zig:639)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink_Subclass$$function$$1.apply(KafkaSqlSink_Subclass$$function$$1.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.apicurio.registry.logging.LoggingInterceptor.logMethodEntry(LoggingInterceptor.java:55)
	at io.apicurio.registry.logging.LoggingInterceptor_Bean.intercept(LoggingInterceptor_Bean.zig:327)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink_Subclass.processMessage(KafkaSqlSink_Subclass.zig:596)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink_ClientProxy.processMessage(KafkaSqlSink_ClientProxy.zig:128)
	at io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage.lambda$startConsumerThread$1(KafkaSqlRegistryStorage.java:282)
	at io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage$$Lambda$653/0x000000001c1f6fc0.accept(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage.lambda$startConsumerThread$2(KafkaSqlRegistryStorage.java:256)
	at io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage$$Lambda$577/0x000000009ddd8740.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:866)
Caused by: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "FK_VERSIONS_2: PUBLIC.VERSIONS FOREIGN KEY(CONTENTID) REFERENCES PUBLIC.CONTENT(CONTENTID) (131072)"; SQL statement:
INSERT INTO versions (globalId, tenantId, groupId, artifactId, version, versionId, state, name, description, createdBy, createdOn, labels, properties, contentId) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23506-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.constraint.ConstraintReferential.checkRowOwnTable(ConstraintReferential.java:332)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:274)
	at org.h2.table.Table.fireConstraints(Table.java:995)
	at org.h2.table.Table.fireAfterRow(Table.java:1013)
	at org.h2.command.dml.Insert.insertRows(Insert.java:192)
	at org.h2.command.dml.Insert.update(Insert.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:88)
	at io.apicurio.registry.storage.impl.sql.jdb.UpdateImpl.execute(UpdateImpl.java:44)
	... 44 more

2021-11-321 14:39:29 INFO <> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Content entity imported successfully.
2021-11-321 14:39:29 INFO <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Content entity imported successfully.
2021-11-321 14:39:29 INFO <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Global Rule entity imported successfully.
2021-11-321 14:39:29 INFO <_> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Global Rule entity imported successfully.
2021-11-321 14:39:30 INFO <> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Resetting globalId sequence
2021-11-321 14:39:30 INFO <> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Successfully reset globalId to 262145
2021-11-321 14:39:30 INFO <> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Resetting contentId sequence
2021-11-321 14:39:30 INFO <> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Successfully reset contentId to 262145
```

So although it doesn't accept the empty entry in the zip file, the other entries (versions 1 and 3) are successfully imported.

**Comment by famartinrh** [comment]
well, I'll try to dig a bit to understand exactly why those sql errors.

But anyway an artifact in DISABLED state can be changed to ENABLED bach again, so I think this solution it's not what we need. Maybe temporarily re-enable the artifact version to be able to download the content could be a solution.

While trying this locally I'm having a bunch of build errors, maybe due to the new release, so I'll give this a try and create a new PR to fix the bug addressed in this PR.

Thank you

**Comment by ajborley** [comment]
> But anyway an artifact in DISABLED state can be changed to ENABLED bach again, so I think this solution it's not what we need. Maybe temporarily re-enable the artifact version to be able to download the content could be a solution.

Yeah, that could be a good solution here 👍  It would definitely be better if the artifact contents could get exported.

> While trying this locally I'm having a bunch of build errors, maybe due to the new release, so I'll give this a try and create a new PR to fix the bug addressed in this PR.

Yes, I have the same - I've been testing this on the 2.1.0.Final tag, as I find I can't build it after this. I raised an issue for this yesterday: https://github.com/Apicurio/apicurio-registry/issues/2024

**Comment by ajborley** [comment]
Superseded by https://github.com/Apicurio/apicurio-registry/pull/2027 (which is a much better solution and also fixes the compilation issue). Closing this PR.

**Pull request closed without merging**
