### PR TITLE
Added QE tests for new features in downstream release (Fuse 7.6)

### PR DESCRIPTION
**Pull request by EricWittmann**
Added some additional QE tests to cover the features added to the registry since the last downstream release.  This includes:

* Test for JSON Schema serdes
* Test for Protobuf (FD) serdes
* Tests for all artifact types (not just Avro)
* Tests for enable/disable
* Tests for deprecated
* Coverage for `testUpdateArtifact`
* Coverage for `getArtifactVersionByContent`
* Specific test for `deleteAllGlobalRules` (functionality was broken)

### CODE REVIEW

**Comment by EricWittmann** [comment]
@Frawless This PR represents the changes for QE tests for Fuse 7.6 if you want to have a look at some point.  Most of the needed coverage is there already I think, but I have to take another pass to make sure.

**Comment by see-quick** [comment]
Adding for reminder from meeting 
- need to add some test-cases for Protobuff ser-des 
- will do review later...

**Comment by EricWittmann** [comment]
>     * need to add some test-cases for Protobuff ser-des

Should be done now.  Waiting on CI to see if I messed anything up. :)

**Comment by EricWittmann** [comment]
I have to merge this because there are bug fixes and I need to do a build tomorrow.

**Comment by Frawless** [comment]
Sorry, we were overwhelmed by another work, but since circle-ci was green I think it's fine. We will try to run them in our pipelines with ocp4 and we will see if some changes will be needed. Thank you for that PR, good job!

**Comment by EricWittmann** [comment]
No need to apologize - just wanted to let you know why I merged without waiting for a review. :)

**Comment by EricWittmann** [comment]
@see-quick and @Frawless please note that I have created the OpenShift template for this next release of Service Registry.  You can find it here:

https://github.com/Apicurio/apicurio-registry/blob/1.1.x-redhat/distro/openshift-template/service-registry-template.yml

Note the branch is `1.1.x-redhat`.  This is a template that references the most recent productized image that was built today (Feb 28).  It *should* be ready for testing.  At your convenience. :)

**Pull request merged**
