### PR TITLE
Remove infinispan.version duplicated definition

### LINKED ISSUE #939: Duplicate definition of infinispan.version in pom.xml
The <infinispan.version> has duplicate definition
dependabot updates the first one, but build using second that's wrong behavior and need to be fixed
https://github.com/Apicurio/apicurio-registry/blob/399487f37d15fab57fc19c174add9d7323fd6e31/pom.xml#L133

https://github.com/Apicurio/apicurio-registry/blob/399487f37d15fab57fc19c174add9d7323fd6e31/pom.xml#L162

### PR DESCRIPTION
**Pull request by dmvolod**
Fixes #939

### CODE REVIEW

**Comment by EricWittmann** [comment]
This change results in some (seemingly relevant) build failures.

**Comment by dmvolod** [comment]
@EricWittmann it seems to error looks like there, but don't understand why server not fails early and don't catch on startup
```
INFO: Registry > 2020-10-22 15:57:34,335 ERROR [org.inf.CLUSTER] (jgroups-8,localhost-60050) ISPN000475: Error processing response for request 26 from localhost-25468: org.infinispan.commons.CacheException: ISPN000936: Class 'java.util.HashMap' blocked by deserialization white list. Adjust the configuration serialization white list regular expression to include this class.
```

**Comment by dmvolod** [comment]
@EricWittmann error has been fixed. Please review

**Review by EricWittmann — APPROVED** [review]

**Comment by EricWittmann** [comment]
Thanks!

**Pull request merged**
