### PR TITLE
changes for the proposed tag structure

### PR DESCRIPTION
**Pull request by riprasad**

### CODE REVIEW

**Comment by riprasad** [comment]
@EricWittmann I could see you have already done the changes for the 1.3.x branch around a month ago.

**Comment by EricWittmann** [comment]
Looks pretty good, @riprasad - what about the Verify workflow.  Do you think a similar script-based approach makes sense there?  With the idea that on a maintenance branch we would want the tag to be `<branchname>-snapshot` instead of `latest-snapshot`.  So e.g. if we have a `3.1.x` branch someday, any Verify builds should tag and push docker images with a tag of `3.1.x-snapshot`.

**Comment by riprasad** [comment]
> Looks pretty good, @riprasad - what about the Verify workflow. Do you think a similar script-based approach makes sense there? With the idea that on a maintenance branch we would want the tag to be `<branchname>-snapshot` instead of `latest-snapshot`. So e.g. if we have a `3.1.x` branch someday, any Verify builds should tag and push docker images with a tag of `3.1.x-snapshot`.

@EricWittmann I was thinking to have dedicated very workflows for the maintenance branches. But, it does make sense to have a similar script-based approach for the verify workflow as well. 

Also, one thing to keep in mind is this will work as long as the build variants doesn't change. if it does, just let me know and I'll do the necessary changes.

**Review by EricWittmann — APPROVED** [review]

**Comment by EricWittmann** [comment]
Looks good, thanks @riprasad !

**Pull request merged**
