### PR TITLE
Refactor to decouple JsonSchemaDiffLibrary from registry objects.

### PR DESCRIPTION
**Pull request by blacktooth**
This is related to [Issue](https://github.com/Apicurio/apicurio-registry/issues/1214)

This change will further decouple jsonschema compatibility from registry types.

I will submitting subsequent PR to move the files to different location.

Context on this is also available on [PR](https://github.com/Apicurio/apicurio-registry/pull/1245#event-4410863472)

### CODE REVIEW

**Review by famartinrh — APPROVED** [review]
looks good

**Comment by EricWittmann** [comment]
@jsenko Can you have a look at this?

**Review by jsenko — APPROVED** [review]
LGTM

**Comment by blacktooth** [comment]
Thanks a lot for reviewing and merging this!

**Pull request merged**
