### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yeralin**
Add info about setting `prod` profile when using PostgreSQL JDBC driver.

### CODE REVIEW

**Comment by EricWittmann** [comment]
@jsenko can you pls verify?

**Comment by yeralin** [comment]
Related to #284

**Comment by jsenko** [comment]
Hi, 
The question is, whether we want to bake-in the quarkus profile into the images we release. My original idea was to set the profile during the build using a maven parameter. That's why the *prod/dev* possibilities are mentioned in the context of the build itself, and not as environment variables. The main advantage would be to exclude some deps. in case we do a native build.

I've checked the images and it looks like we're not doing that, so I think we should add the info to the README, but because the option affects other backends in addition to JPA, I'd move the information into a separate section higher up.

**Comment by EricWittmann** [comment]
Or should I just update the release script to add `-Pprod` when building the docker image?

**Comment by EricWittmann** [comment]
And if the answer to that is "yes", then should it **always** be `-Pprod` even when pushing a snapshot build to docker?

For reference, I have two "release" scripts - one for doing a full release and one for doing a snapshot release.  They both push images to docker hub, but with slightly different tags on the images.  The snapshot release I believe pushes `latest` and `latest-snapshot` while the full release script pushes `latest` and `latest-release`.

**Comment by jsenko** [comment]
We should use `-Pprod` even for snapshot builds. The *dev* profile is intended for mostly local testing during development.

**Comment by EricWittmann** [comment]
OK in that case I think we should probably not accept this PR and instead we should update the release scripts to make sure we build with `-Pprod` enabled for all cases.  And I can do a snapshot release that will push new images to docker.  The `latest-release` tag doesn't exist yet, but I can probably checkout the latest release tag, produce the docker images, and push them.

Agreed?

**Comment by EricWittmann** [comment]
@jsenko I've updated the release scripts to add `-Pprod` for both snapshot and release builds.  So going forward I dont' think we need to document this.  If you agree pls give me a +1 so I can close out this PR.

@yeralin thanks for raising this issue!

**Comment by EricWittmann** [comment]
OK great - @yeralin I'm going to close this.  **Please** re-open this if the next release of the registry continues to have this issue.

**Comment by EricWittmann** [comment]
For reference, the release script for this project is here:

https://github.com/Apicurio/apicurio-release/blob/master/release-registry.sh

I believe that `-Pprod` is now indicated in all the correct places.

**Pull request closed without merging**
