### PR TITLE
Fix date format in v2 api

### PR DESCRIPTION
**Pull request by carlesarnal**

### CODE REVIEW

**Comment by EricWittmann** [comment]
These changes are against classes generated by the Studio codegen feature.  I have changed the codegen so that it includes the `@JsonFormat` annotation.  However, it adds the annotation to the field instead of the getter/accessor.  @carlesarnal Can you try moving the annotation to the field and let me know if that works as well?

**Comment by carlesarnal** [comment]
> These changes are against classes generated by the Studio codegen feature. I have changed the codegen so that it includes the `@JsonFormat` annotation. However, it adds the annotation to the field instead of the getter/accessor. @carlesarnal Can you try moving the annotation to the field and let me know if that works as well?

Yes, having the `@JsonFormat` also works. How do you want to proceed, re-generate the classes or a quick commit to change this?

**Comment by EricWittmann** [comment]
Let me regenerate the classes and you can review/test for me?

**Comment by EricWittmann** [comment]
Fixed by updating the Studio codegen and regenerating.  https://github.com/EricWittmann/apicurio-registry/pull/24

**Pull request closed without merging**
