### PR TITLE
Use concurrent set.

### PR DESCRIPTION
**Pull request by alesj**

### CODE REVIEW

**Comment by alesj** [comment]
This fixes a concurrency bug.
The stream is parallel, whereas TreeSet is not.

**Comment by EricWittmann** [comment]
@alesj Do you consider this a fix for a blocker?  Do we have a specific test for this problem?  Can you provide more details?  We would need to justify any changes to the 1.2.x so that @paoloantinori can know whether it's something that needs to be pulled in for GA.  It's quite late for that now.

**Comment by alesj** [comment]
In a cluster, returned stream of all keys is parallel, where TreeSet is not
(multithreaded).
I saw it hanging or really slowly processing keys in my multi-node cluster
test.
With concurrent set we should be fine.
Plus it’s really minor/trivial change, with big value/fix.

**Comment by EricWittmann** [comment]
This only affects "list all artifact IDs" - do we know if any runtime use-cases (vs. e.g. data migration use-cases) leverage that functionality?

BTW - this is a good change but we've already produced the final GA builds.

**Comment by alesj** [comment]
#664 also includes this fix / pr

**Pull request closed without merging**
