### PR TITLE
 Kiota sync client

### PR DESCRIPTION
**Pull request by andreaTP**
Bump the Kiota version and generate the sync client for Registry.

### CODE REVIEW

**Comment by andreaTP** [comment]
@jsenko do you know why Quodana is complaining?

**Comment by jsenko** [comment]
> @jsenko do you know why Quodana is complaining?

Don't know, I haven't seen that error before... maybe it's confused by generated artifacts.
Do you have Idea installed? Maybe you can try opening the project and see if it works.
If this is a problem we can disable Qodana.

**Comment by andreaTP** [comment]
The failure seems to be related to the fact that I renamed the module ... not sure how this impact

**Comment by andreaTP** [comment]
@carlesarnal I think this is ready to merge, wdyt? Thanks again for the support!

**Comment by carlesarnal** [comment]
If CI is happy (apart from qodana), I'm happy :)

**Review by carlesarnal — APPROVED** [review]
Nice work!

**Review by EricWittmann — APPROVED** [review]

**Pull request merged**
