### PR TITLE
add docs for artifact references (phase 1 - API and maven plugin)

### PR DESCRIPTION
**Pull request by smccarthy-ie**
Adds new docs on: 
 - Introduction to artifact references
 - Creating an artifact reference using the REST API
 - Creating an artifact reference using the Maven plugin
 - How artifact references work with SerDes (Avro, protobuf, and JSON Schema)

### CODE REVIEW

**Review by carlesarnal — APPROVED** [review]
LGTM

**Comment by smccarthy-ie** [comment]
Thanks @carlesarnal for the review and approval. Looks like I can't merge this PR because 2 required checks have not run. But AFAICT, these checks do not apply in this case, so this docs-only PR is blocked?

**Comment by carlesarnal** [comment]
> Thanks @carlesarnal for the review and approval. Looks like I can't merge this PR because 2 required checks have not run. But AFAICT, these checks do not apply in this case, so this docs-only PR is blocked?

I can manually merge if you think this is ready (I think yes). Just ping me whenever you want to merge it.

**Comment by smccarthy-ie** [comment]
Great, thanks @carlesarnal  This one is ready to merge :)

**Pull request merged**
