### PR TITLE
Initial implementation CNCF Schema Registry API

### PR DESCRIPTION
**Pull request by famartinrh**
first take on the cloudevents SchemaRegistry API.
JaxRS interface created with Apicurio Studio, very basic implementation and one test.

I had to add methods with CRUD operations for the artifact groups.
In memory storage is implemented and sql is a work in progress.

### CODE REVIEW

**Comment by EricWittmann** [comment]
@famartinrh Can you update this PR to resolve the conflicts?

**Comment by EricWittmann** [comment]
Should we relocate all of the "compat" APIs under a single endpoint context?  Perhaps everything under `compat`?  Or maybe all APIs under the same umbrella, including our own core API?  Here is the list of APIs we currently support:

* Apicurio Registry API v1 :: `/api/v1/`
* Apicurio Registry API v2 :: `/api/v2/`
* Confluent Schema Registry API :: `/api/ccompat/`
* IBM Schema Registry API :: `/api/ibmcompat/`
* CNCF Schema Registry v0.1 :: `/api/cncf/v0.1/`

@Apicurio/developers What do we think about this?  I'll start with a suggestion, since I think we need some consistency here, and 2.0 is a good opportunity to get this "right":

Proposed template for all APIs current and future:

`/apis/{apiId}/{apiVersion}/`

So this would result in the above list changing to this:

* Apicurio Registry API v1 :: `/apis/apicurio/v1/`
* Apicurio Registry API v2 :: `/apis/apicurio/v2/`
* Confluent Schema Registry API :: `/apis/confluent/v6/` (@carlesarnal what is the version of the confluent API we support?)
* IBM Schema Registry API :: `/apis/ibm/v1/` (not sure what the version is here - we'll need to check with IBM)
* CNCF Schema Registry v0.1 :: `/apis/cncf/v0.1/`

Or instead of `apicurio` above we could perhaps use `core` or something else?

I'm interested in opinions on this.

Also we've been encouraged to not use "confluent" in the endpoint, but I'm not sure if that's due to concerns about trademarking or just not wanting to advertise our competition.  @paoloantinori thoughts?  So we could stick with "ccompat" if we want to be safe.

**Comment by famartinrh** [comment]
I think that's a good idea, it will make all our various REST APIs much more consistent. I don't have an strong opinion on using `apicurio` or `core`.

btw that template for APIs prefixes is similar to the one used in kubernetes... which I think it's good :)

**Comment by jsenko** [comment]
I think it's a great idea as well. A few comments:
- I'm not sure that we need to name our (Apicurio) API. Using `/apis/vX` and `/apis/compat/{otherApiId}/{apiVersion}/` could reinforce the idea that it is a preferred choice for new users. So I wouldn't be against sacrificing consistency here. On the other hand this may not have that much influence, and in that case I would prefer using `apicurio` instead of something generic, if other APIs use recognizable names.
- CNCF v0.1 should probably use `/apis/cncf/v0` for consistency.
- Confluent API version was `5.5.0` last I updated it.

**Comment by paoloantinori** [comment]
+1 to leave "confluent" name out of the codebase
possible suggestion: are we allowing to turn on and off all those apis with some kind of feature flag? (ideally an env var)

**Comment by carlesarnal** [comment]
>  * Confluent Schema Registry API :: `/apis/confluent/v6/` (@carlesarnal what is the version of the confluent API we support?)

Except for the hard and soft deletes feature, we're aligned with v6.x.

Just a few comments: 

- Big +1 to having everything under the same umbrella for consistency.
- +1 to CNCF v0.1 using /apis/cncf/v0 for consistency.
- I'd prefer to use core instead of apicurio for our API (or maybe main?).

**Comment by famartinrh** [comment]
API path updated to the new version `v0` we agreed.

One thing I'm not 100% convinced is the groups handling, this API, unlike our core API, allows to manage Schema Groups as an entity. For that I updated the storage layer with crud operations for groups...

However, given this thing is experimental I think it could be ok as it is now, and testing, improvements,... can be done later, unless you have some feedback now :)

**Comment by EricWittmann** [comment]
Given our other priorities we should just merge this as a "experimental" feature and come back to it a bit later.  I could see us adding in the groups management concepts to the v2 API maybe.

**Comment by EricWittmann** [comment]
Can I merge this without it breaking anything unrelated to the CNCF api?

**Comment by famartinrh** [comment]
No, I just realized this is not finished, most of the storages are missing to be implemented

**Pull request closed without merging**
