### PR TITLE
Change content canonicalizer for AVRO to improve schema evolution and…

### PR DESCRIPTION
**Pull request by AndreaScarselli**
Implements a new AVRO content canonicalizer that addresses the issues reported in #300 .

In particular, the new Content Canonicalizer:

1. Consider different 2 schemas that have the same fields in different order
2. Considers equal 2 schemas that have the same attribute in the root in a different order
3. Considers equals a schema that has the namespace in the `name`, and a schema that has the same `name` and the namespace in the `namespace` field
4. Considers equals 2 schemas that only differ by the optional attributes (e.g`doc`) both in the root and in the fields

### CODE REVIEW

**Comment by carlesarnal** [comment]
Thank you very much for the PR @AndreaScarselli. I really feel this implementation is better than the current one and thus should replace it. That said we need an upgrade process for existing installations. The question here is, how do you want to proceed? I can merge this PR and work on the upgrade process or, if you want, I can let you add the process as well if you want to contribute it?

Let me know what you think!

Thanks again.

**Comment by AndreaScarselli** [comment]
> Thank you very much for the PR @AndreaScarselli. I really feel this implementation is better than the current one and thus should replace it. That said we need an upgrade process for existing installations. The question here is, how do you want to proceed? I can merge this PR and work on the upgrade process or, if you want, I can let you add the process as well if you want to contribute it?
> 
> Let me know what you think!
> 
> Thanks again.

Hi @carlesarnal , 

Thank you for your answer. What exactly is this _upgrade process_ ? If I can have some reference I can have a look and try to work on it.

**Comment by carlesarnal** [comment]
> > Thank you very much for the PR @AndreaScarselli. I really feel this implementation is better than the current one and thus should replace it. That said we need an upgrade process for existing installations. The question here is, how do you want to proceed? I can merge this PR and work on the upgrade process or, if you want, I can let you add the process as well if you want to contribute it?
> > Let me know what you think!
> > Thanks again.
> 
> Hi @carlesarnal ,
> 
> Thank you for your answer. What exactly is this _upgrade process_ ? If I can have some reference I can have a look and try to work on it.

Essentially, something similar to `[this](https://github.com/Apicurio/apicurio-registry/blob/main/app/src/main/java/io/apicurio/registry/storage/impl/sql/upgrader/ReferencesCanonicalHashUpgrader.java)`. With this PR, we're changing the way some data is "created", but there is already existing data that must be upgraded. Those upgraders are responsible for that upgrade process. As I said, if you want to try, fine, but, if not, I'm happy implementing it for this PR, the upgrade process is pretty custom. In any case, thank you again for trying to contribute.

**Comment by AndreaScarselliAx** [comment]
> > > Thank you very much for the PR @AndreaScarselli. I really feel this implementation is better than the current one and thus should replace it. That said we need an upgrade process for existing installations. The question here is, how do you want to proceed? I can merge this PR and work on the upgrade process or, if you want, I can let you add the process as well if you want to contribute it?
> > > Let me know what you think!
> > > Thanks again.
> > 
> > 
> > Hi @carlesarnal ,
> > Thank you for your answer. What exactly is this _upgrade process_ ? If I can have some reference I can have a look and try to work on it.
> 
> Essentially, something similar to `[this](https://github.com/Apicurio/apicurio-registry/blob/main/app/src/main/java/io/apicurio/registry/storage/impl/sql/upgrader/ReferencesCanonicalHashUpgrader.java)`. With this PR, we're changing the way some data is "created", but there is already existing data that must be upgraded. Those upgraders are responsible for that upgrade process. As I said, if you want to try, fine, but, if not, I'm happy implementing it for this PR, the upgrade process is pretty custom. In any case, thank you again for trying to contribute.

Hi @carlesarnal , if you are happy to implement it I would leave it to you then. I will keep notifications on for this PR so if I can help with something I am easily reachable.

Thank you so much again for reviewing this MR.

**Comment by AndreaScarselli** [comment]
> > > Thank you very much for the PR @AndreaScarselli. I really feel this implementation is better than the current one and thus should replace it. That said we need an upgrade process for existing installations. The question here is, how do you want to proceed? I can merge this PR and work on the upgrade process or, if you want, I can let you add the process as well if you want to contribute it?
> > > Let me know what you think!
> > > Thanks again.
> > 
> > 
> > Hi @carlesarnal ,
> > Thank you for your answer. What exactly is this _upgrade process_ ? If I can have some reference I can have a look and try to work on it.
> 
> Essentially, something similar to `[this](https://github.com/Apicurio/apicurio-registry/blob/main/app/src/main/java/io/apicurio/registry/storage/impl/sql/upgrader/ReferencesCanonicalHashUpgrader.java)`. With this PR, we're changing the way some data is "created", but there is already existing data that must be upgraded. Those upgraders are responsible for that upgrade process. As I said, if you want to try, fine, but, if not, I'm happy implementing it for this PR, the upgrade process is pretty custom. In any case, thank you again for trying to contribute.

Hi @carlesarnal  , if you are happy to implement it I would leave it to you then. I will keep notifications on for this PR so if I can help with something I am easily reachable.

Thank you so much again for reviewing this MR.

**Comment by carlesarnal** [comment]
> > > > Thank you very much for the PR @AndreaScarselli. I really feel this implementation is better than the current one and thus should replace it. That said we need an upgrade process for existing installations. The question here is, how do you want to proceed? I can merge this PR and work on the upgrade process or, if you want, I can let you add the process as well if you want to contribute it?
> > > > Let me know what you think!
> > > > Thanks again.
> > > 
> > > 
> > > Hi @carlesarnal ,
> > > Thank you for your answer. What exactly is this _upgrade process_ ? If I can have some reference I can have a look and try to work on it.
> > 
> > 
> > Essentially, something similar to `[this](https://github.com/Apicurio/apicurio-registry/blob/main/app/src/main/java/io/apicurio/registry/storage/impl/sql/upgrader/ReferencesCanonicalHashUpgrader.java)`. With this PR, we're changing the way some data is "created", but there is already existing data that must be upgraded. Those upgraders are responsible for that upgrade process. As I said, if you want to try, fine, but, if not, I'm happy implementing it for this PR, the upgrade process is pretty custom. In any case, thank you again for trying to contribute.
> 
> Hi @carlesarnal , if you are happy to implement it I would leave it to you then. I will keep notifications on for this PR so if I can help with something I am easily reachable.
> 
> Thank you so much again for reviewing this MR.

Getting back to this. Fine by me, I will update the PR with the required changes to add the upgrader.

**Comment by carlesarnal** [comment]
Finally got into this. Once CI passes, I'll merge the PR. We don't need the upgrader in its old form. We're going to work on an upgrade process that will migrate old data from Registry 2.x installations to Registry 3.x installations.

Thanks for your patience @AndreaScarselli!

**Review by carlesarnal — APPROVED** [review]

**Comment by AndreaScarselli** [comment]
Hi @carlesarnal Thank you so much for your answer and for the approval.

Will this new canonicalizer be part of version 3.x? Can we have an estimation on when a version containing this canonicalizer will be published?

**Comment by carlesarnal** [comment]
> Hi @carlesarnal Thank you so much for your answer and for the approval.
> 
> Will this new canonicalizer be part of version 3.x? Can we have an estimation on when a version containing this canonicalizer will be published?

Yes, this new canonicalizer will be part of version 3. If we want to back port it, that takes us back to the upgrader world, and I would like to avoid that if possible. About the version, anytime a PR is merged into main, a new `latest-snapshot` image is published. About an actual release, we don't have an ETA yet for it, for it will be for sure into the next year.

**Comment by carlesarnal** [comment]
Hi, 
We probably won't have a 3.0.0 release done until March at least. We're currently considering backporting this to 2.x and doing a new release there. I'll let you know the decision here.

**Comment by AndreaScarselli** [comment]
Thank you @carlesarnal

**Pull request merged**
