### PR TITLE
Improvements on Nats Serdes

### PR DESCRIPTION
**Pull request by souravagrawal**
Fixes https://github.com/Apicurio/apicurio-registry/issues/5215

### CODE REVIEW

**Comment by carlesarnal** [comment]
@souravagrawal I'm missing test cases for the newly added methods. You have the exiting one as an example, could you please add tests for the other methods as well?

**Comment by sourabhaggrawal** [comment]
> Implement nats avro serdes #5195

Hi @carlesarnal Yes I have added them now

**Comment by sourabhaggrawal** [comment]
Hi @carlesarnal I do not understand why test is failing, there is no test with expected value as false in AvroNatsSerdeIT.

**Comment by carlesarnal** [comment]
@sourabhaggrawal the tests results are apparently not consistent. Can you please take a look?

**Comment by sourabhaggrawal** [comment]
Hi @carlesarnal apologies for delay in response, test case were working in my setup not sure why its not working here.
I have anyways added a change to check to see if rest of the tests goes through, can you please initiate the workflow once ?

**Comment by sourabhaggrawal** [comment]
Hi @carlesarnal can you triggered the workflow once again ? It failed again because of indentation and I have pushed a commit with fix. 
TIA

**Comment by sourabhaggrawal** [comment]
HI @carlesarnal can you initiate the workflow again, it has not run after my latest commit.

**Comment by sourabhaggrawal** [comment]
Thank you @carlesarnal

**Pull request merged**
