### PR TITLE
Override Keycloak and Netty dependencies

### PR DESCRIPTION
**Pull request by EricWittmann**

### CODE REVIEW

**Review by riprasad — CHANGES_REQUESTED** [review]
I re-ran the scan and found out that all the vulnerability still exists. On doing a quick dependecy:tree, found out that the vulnerable versions of dependencies are still pulled transitively.

**Comment by EricWittmann** [comment]
Which modules are still pulling the deps transitively?  I've updated the `app` module but I'm guessing there are other modules that also need updating?

**Comment by riprasad** [comment]
> Which modules are still pulling the deps transitively? I've updated the `app` module but I'm guessing there are other modules that also need updating?

Below are the modulles that still pulls the older version of the dependencies:-

**keycloak-core** -> apicurio-registry-common, apicurio-registry-utils-kafka, apicurio-registry-utils-import-export, apicurio-registry-client, apicurio-registry-serde-common, apicurio-registry-serdes-avro-serde, apicurio-registry-serdes-protobuf-serde, apicurio-registry-serdes-jsonschema-serde, apicurio-registry-maven-plugin, apicurio-registry-utils-tests, apicurio-registry-cli, apicurio-registry-utils-converter, apicurio-registry-storage, apicurio-registry-distro-connect-converter

**resteasy-core** -> apicurio-registry-storage

**netty-handler** and **netty-codec-http2** -> apicurio-registry-storage, apicurio-registry-utils-exportV1, apicurio-registry-common

I have added the dependencies in the <dependencyManagement> section of the root pom and now every module uses the overridden versions of these dependencies.

**Comment by EricWittmann** [comment]
I honestly didn't know putting the overrides in the root pom.xml's `dependencyManagement` section would have that effect.  Nice.

I'll work on the test errors.  Also happy if other @Apicurio/developers had a look.  :)

**Comment by EricWittmann** [comment]
Closing in favor of https://github.com/Apicurio/apicurio-registry/pull/1569

**Pull request closed without merging**
