### PR TITLE
Updates to the UI based on UX designs.

### PR DESCRIPTION
**Pull request by EricWittmann**

### CODE REVIEW

**Review by jsenko — COMMENTED** [review]
Looks good, but there are test failures

**Review by jsenko — APPROVED** [review]
LGTM

**Comment by famartinrh** [comment]
@EricWittmann tests should pass now

**Comment by EricWittmann** [comment]
Looks like **almost**!  :)

image

**Comment by EricWittmann** [comment]
I'm going to merge anyway, and we can work out the test problem (if there is one) later.

**Pull request merged**
