### PR TITLE
JR-215: Adds rule precedence table. Adds validity-rule value NONE.

### PR DESCRIPTION
**Pull request by bredamc**

### CODE REVIEW

**Comment by bredamc** [comment]
@EricWittmann @smccarthy-ie Ready for you to review:
 - Added a table to show the order of precedence for registry rules.
 - Added the value "NONE" to the list of validity-rule values.

**Comment by EricWittmann** [comment]
This looks good to me.  Although I wonder - should we have a note somewhere about the purpose of the `None` option?  How it's useful to "disable" a rule at the artifact level, to override an enabled/configured global rule?

**Comment by bredamc** [comment]
Added a "Rule precedence" section to the "Apicurio Registry content rules" chapter, and explained the `NONE` rule value there.

**Comment by bredamc** [comment]
@EricWittmann @smccarthy-ie Ready for the (hopefully final!) review now, please and thank you :)

**Comment by EricWittmann** [comment]
lgtm

**Comment by EricWittmann** [comment]
Thanks @bredamc !

**Pull request merged**
