### PR TITLE
Add ccompat v7 api

### PR DESCRIPTION
**Pull request by carlesarnal**
### Included
- Added and implemented ccompat API v7 operations.
- Updated wire dependencies to the latest version.
- Re-structured tests for ccompat client and rest api.

### CODE REVIEW

**Comment by carlesarnal** [comment]
Creating in draft status to get feedback from the integration tests (the unit tests should pass).

**Review by EricWittmann — APPROVED** [review]

**Comment by EricWittmann** [comment]
Nice that we're supporting two different versions of confluent schema registry api now.  We should probably mark v6 as deprecated somewhere.

**Comment by EricWittmann** [comment]
I've re-triggered the tests because two were failing.  If the checks pass, please go ahead and merge.  @carlesarnal

**Comment by carlesarnal** [comment]
> Nice that we're supporting two different versions of confluent schema registry api now. We should probably mark v6 as deprecated somewhere.

Yeah, that sounds like a good idea. But it's probably a documentation thing rather than something in the code.

**Pull request merged**
