### PR TITLE
Kiota client

### PR DESCRIPTION
**Pull request by andreaTP**
Opening as Draft to show the progress on this.

Current status:
I'm close to having all of the tests in `app` passing, currently, there are some missing in `RegistryClientTest` (which is the last one).
I likely found a bug in Kiota performing an additional undesired serialization on the content, going to fix it.

### CODE REVIEW

**Comment by carlesarnal** [comment]
@andreaTP don't worry about the conflicts, I'll take them.

**Comment by andreaTP** [comment]
Thanks @carlesarnal , but let me complete at least the `app` module tests before moving on with this (I'm on it!).

**Comment by carlesarnal** [comment]
> Thanks @carlesarnal , but let me complete at least the `app` module tests before moving on with this (I'm on it!).

Sure! Not rushing, just letting you know about the potential conflicts :)

**Comment by smccarthy-ie** [comment]
@andreaTP @carlesarnal 
I'm guessing this will also required updates to the user docs when complete? 
https://www.apicur.io/registry/docs/apicurio-registry/2.4.x/getting-started/assembly-using-the-registry-client.html

**Comment by andreaTP** [comment]
@smccarthy-ie yes, definitely 👍 But let's wait as much as we can on finalizing the docs to get the most stability out of Kiota (Java is not GA yet for them).

**Comment by andreaTP** [comment]
IntelliJ is behaving pretty badly, but there is a workaround to get things working:
image

Ignoring the `client` Maven project gets the IDE back in a usable status.
Please try it out and let me know!

**Review by carlesarnal — APPROVED** [review]
Nice work!

**Pull request merged**
