### PR TITLE
smart rest client - populate base path #1311

### PR DESCRIPTION
**Pull request by famartinrh**

### CODE REVIEW

**Review by carlesarnal — APPROVED** [review]

**Comment by carlesarnal** [comment]
@famartinrh this looks good to me. I'm seeing a failure in the SQL storage. I don't think it's related to the changes here, maybe we need something from master?

**Comment by EricWittmann** [comment]
What if someone puts a layer in between clients and the server that change the URL?  API Management for example.  That's my only concern here.

**Comment by EricWittmann** [comment]
If we want to the client to be really smart, maybe we can (optionally?) try to figure out the URL by trying to hit the new `/system/info` endpoint.

**Comment by famartinrh** [comment]
yes, Eric's approach will make the client really smart, but in the short term, and a easier solution could be to have a config property to "disable the automatic base path append" , wdyt?

**Comment by EricWittmann** [comment]
+1 to having a property that can make the client dumber. :) :)

**Comment by carlesarnal** [comment]
+1 here

**Review by EricWittmann — APPROVED** [review]

**Comment by EricWittmann** [comment]
@famartinrh I've updated the branch so that build checks are triggered again.  They failed the last time.

**Review by carlesarnal — APPROVED** [review]

**Pull request merged**
