### PR TITLE
Push images to quay.io

### PR DESCRIPTION
**Pull request by riprasad**

### CODE REVIEW

**Comment by EricWittmann** [comment]
This looks good, although we're missing the `kafkasql` storage variant, and we also need to update the Verify workflow in addition to the Release workflow - the Verify workflow publishes images tagged with the `latest-snapshot` tag.

**Comment by jsenko** [comment]
Looks good to me (other than what Eric mentioned). 

I'd like to request one related change though (can be done in a separate issue/PR). If I'm correct, we are currently building and pushing images tagged as `latest` from both master and `1.3.x` branches. Since the operator is using latest images it cannot differentiate between latest `2.x` and `1.x` images. Could we consider separate latest tags for each branch or limiting the latest tag for `master` only?

**Review by jsenko — APPROVED** [review]
Looks good to me (other than what Eric mentioned). 

I'd like to request one related change though (can be done in a separate issue/PR). If I'm correct, we are currently building and pushing images tagged as `latest` and `latest-snapshot` from both `master` and `1.3.x` branches. Since the operator is using latest images it cannot differentiate between latest `2.x` and `1.x` images. Could we consider separate latest tags for each branch or limiting the latest tag for `master` only?

**Comment by riprasad** [comment]
@EricWittmann Included the kafkasql storage variant.

 However, I am not clear on the second part. You mentioned that verify workflow publishes images tagged with `latest-snapshot` tag and we need to update the verify workflow. Do we need to tag the images with a different tag and publish, or is it about some other change?

**Comment by EricWittmann** [comment]
@riprasad The verify workflow is pushing images to docker hub.  We should update the verify workflow to **also** publish to Quay.

**Comment by riprasad** [comment]
@EricWittmann I have updated the verify workflow to also publish to Quay

**Review by EricWittmann — APPROVED** [review]

**Comment by EricWittmann** [comment]
Thanks @riprasad

**Pull request merged**
