### PR TITLE
Validate only required subschemas

### PR DESCRIPTION
**Pull request by carlesarnal**

### CODE REVIEW

**Comment by EricWittmann** [comment]
@jsenko can you review?  I'm actually not sure I understand this exactly.

**Comment by Gourav2912** [comment]
> In json schema a given field is not required unless it is explicitly set (just as you can see in the json schema used in the test and modified in the PR). The former validation was trying to validate always the complex fields (those that are json schemas themselves) even if the field was actually not present, causing the validation to fail, even when the field was not required. This now changes that behaviour to only validate those complex fields if the field being validated is actually required. Hope this makes sense.
> 
> I should have added this to the PR description, sorry. I thought that the linked issue description was enough.

@carlesarnal I guess this is partially correct, implementation should be if optional complex object is present it should be validated if not present ignore for validation. With your fix only optional complex object will not be validated even if it present in data.

**Comment by Gourav2912** [comment]
@carlesarnal @EricWittmann @jsenko Request you guys please let me know when this change will be in Master.

**Comment by EricWittmann** [comment]
We discussed this in a review of our outstanding PRs today and agreed that the implementation in this PR is an improvement.  But we agree with you @Gourav2912 that one more iteration on this is needed where we actual do perform validation of optional fields **if we can**.  So if we can resolve the schema for optional fields we will validate them.  But if no schema is resolvable we will skip the field validation without failing.

Let us know if you agree or disagree.

Merging this PR now as it is an improvement.

Further tracking of this can be found here:  https://github.com/Apicurio/apicurio-registry/issues/2583

**Pull request merged**
