### PR TITLE
Remove connect json exclusion

### PR DESCRIPTION
**Pull request by carlesarnal**

### CODE REVIEW

**Comment by EricWittmann** [comment]
@jpechane What do you think about this?  Any feedback on what JARs should be included/excluded?

@carlesarnal Can you quickly explain how you tested this?  Are you using @famartinrh 's test?  Did you try this manually?

**Comment by carlesarnal** [comment]
> @jpechane What do you think about this? Any feedback on what JARs should be included/excluded?
> 
> @carlesarnal Can you quickly explain how you tested this? Are you using @famartinrh 's test? Did you try this manually?

Hi @EricWittmann, yes, I've tested this using @famartinrh test suite.

**Comment by jpechane** [comment]
What happens if both `connect-json` and `jackson` are removed from the connector?

**Comment by EricWittmann** [comment]
I think that's what I did that caused this issue...

**Comment by jpechane** [comment]
ok I tried to remove `jackson-annotations-2.11.2.jar jackson-core-2.11.2.jar`

so my actual JAR list for Debezium MySQL connector + apicurio distribution is
```
CHANGELOG.md                                       debezium-api-1.3.0.Beta2.jar
CONTRIBUTE.md                                      debezium-connector-mysql-1.3.0.Beta2.jar
COPYRIGHT.txt                                      debezium-core-1.3.0.Beta2.jar
LICENSE                                            debezium-ddl-parser-1.3.0.Beta2.jar
LICENSE-3rd-PARTIES.txt                            kotlin-reflect-1.3.72.jar
LICENSE.txt                                        kotlin-stdlib-1.3.72.jar
README.md                                          kotlin-stdlib-common-1.3.72.jar
annotations-13.0.jar                               medeia-validator-core-1.1.1.jar
antlr4-runtime-4.7.2.jar                           medeia-validator-jackson-1.1.1.jar
apicurio-registry-common-1.3.1.Final.jar           mysql-binlog-connector-java-0.23.1.jar
apicurio-registry-rest-client-1.3.1.Final.jar      mysql-connector-java-8.0.16.jar
apicurio-registry-utils-converter-1.3.1.Final.jar  okhttp-3.14.9.jar
apicurio-registry-utils-serde-1.3.1.Final.jar      okio-1.17.2.jar
avro-1.10.0.jar                                    protobuf-java-3.13.0.jar
commons-compress-1.20.jar                          retrofit-2.9.0.jar
converter-jackson-2.9.0.jar
```

and the Avro converter wroks correctly

**Comment by EricWittmann** [comment]
OK I've gotten lost in this now.  What does this mean for the Apicurio connect distro?  :)

**Comment by jpechane** [comment]
That you should remove both `connect-json` and above mentioned jackson files. Those are still present in 1.3.1.Final

**Comment by EricWittmann** [comment]
OK but isn't that exactly what we did in version 1.3.1.Final?

https://github.com/Apicurio/apicurio-registry/blob/1.3.1.Final/distro/connect-converter/src/assembly/converter-distribution.xml#L21-L22

And that change resulted in https://github.com/Apicurio/apicurio-registry/issues/864 .... 

What am I missing?

**Comment by jpechane** [comment]
1.3.1.Final removed `connect-json` but _kept_ jackson files. If I try to manually remove the jackson files then the reproted issue disappears.

**Comment by carlesarnal** [comment]
> 1.3.1.Final removed `connect-json` but **kept** jackson files. If I try to manually remove the jackson files then the reproted issue disappears.

Ok, let me try excluding both connect-json and jackson.

**Comment by carlesarnal** [comment]
> > 1.3.1.Final removed `connect-json` but **kept** jackson files. If I try to manually remove the jackson files then the reproted issue disappears.
> 
> Ok, let me try excluding both connect-json and jackson.

Ok, I see the real problem now. We weren't excluding jackson since we added the exclusion like `com.fasterxml.jackson:*:*`. Changed to the proper format, tested, and everything is working fine.

**Comment by EricWittmann** [comment]
I see - so I had ***intended*** to do exactly what Jiri suggested but I messed it up.  :)  Man I really thought I double checked that and everything.  Clearly I didn't.  Sorry, my bad.

**Review by EricWittmann — APPROVED** [review]

**Pull request merged**
