### PR TITLE
Support for SQL Server (by matthyx)

### PR DESCRIPTION
**Pull request by EricWittmann**

### CODE REVIEW

**Comment by EricWittmann** [comment]
@matthyx Here is a final PR with SQLServer support.  Thanks for your contribution!  I've fixed up a few minor things and all the tests are green.

**Comment by EricWittmann** [comment]
Well, all the tests are green locally, but somehow I messed up the `Makefile` which is causing CI/CD issues.  I just need to figure that out and then we're good I think.

**Comment by matthyx** [comment]
@EricWittmann awesome, thanks for making it happen and for your trust!

**Comment by vsevel** [comment]
fantastic @matthyx

**Pull request merged**
