### PR TITLE
chore(Kiota): Upgraded Kiota from 1.19.1 to 1.20.0

### PR DESCRIPTION
**Pull request by EricWittmann**

### CODE REVIEW

**Comment by andreaTP** [comment]
Since you are at it:
https://github.com/Apicurio/apicurio-registry/blob/417dde2c3cd63f1ad1bfde72997e6bad563d7891/pom.xml#L267

**Comment by EricWittmann** [comment]
> Since you are at it:
> 
> https://github.com/Apicurio/apicurio-registry/blob/417dde2c3cd63f1ad1bfde72997e6bad563d7891/pom.xml#L267

Isn't that change already in my PR?

**Review by andreaTP — APPROVED** [review]
You are right, I missed it, thanks!

**Comment by EricWittmann** [comment]
Forcibly exclude the compression handler eh?

**Comment by andreaTP** [comment]
> Forcibly exclude the compression handler eh?

Correct ...
Should we support compression instead?

**Comment by EricWittmann** [comment]
Probably so, but for now we'll disable in the client.  I'll open a GH issue for enabling compression.

**Pull request merged**
